# VERSE: MAKEFILE
# This is the comprehensive, top-level Makefile for the entire VERSE project.
#
# Targets:
# - verse-client: Main game client with UI
# - verse: Core engine/server
# - proxy: HTTP proxy for server instances
# - starfighter: Space combat game
# - render-test: Test program for rendering
# - layer-viewer: Slice viewer for generated worlds
# - world-generation-benchmark: Benchmark suite for world generation
# - world-editor-renderer-benchmark: Benchmark for world editor rendering
# - wasm: Build WebAssembly viewer into assets/ (requires emscripten)
# - clang: Build verse-client with clang
# - clang-verse: Build verse with clang

# Compiler selection
CC ?= gcc
CLANG = clang

UNAME_S := $(shell uname -s 2>/dev/null || echo unknown)
NOISE_INCLUDES = -I$(CURDIR)/src/noise-c/include -I$(CURDIR)/src

# Optimization level. There was no -O flag anywhere in this file, which means every target built at
# clang's default of -O0: the tests, the profilers, and the verse-client binary a player runs.
#
# It is worth being concrete about the cost, because the number is large and it silently framed every
# performance decision made here. One 128^3 wilderness world takes 6428ms at -O0 and 1882ms at -O2,
# best of three runs each, and the two worlds are identical — same FNV-1a hash over all 2,097,152
# voxels, same solid count. So roughly two thirds of the world generation budget was the build, not
# the algorithm, and any measurement taken before this line existed overstates the cost of the code
# it was blaming by about 3.4x.
#
# Overridable, so a profile or a bisect can pin it: make OPTFLAGS=-O0. The debug target appends
# -g -O0 after this, and the last -O on the command line is the one clang honours, so it still wins.
OPTFLAGS ?= -O2

# Platform include/lib flags (Homebrew on macOS, pkg-config on Linux)
ifeq ($(UNAME_S),Darwin)
  BREW_PREFIX ?= $(shell brew --prefix 2>/dev/null || echo /opt/homebrew)
  COMMON_CFLAGS = -Wall -Wextra $(NOISE_INCLUDES) \
    -I$(BREW_PREFIX)/include \
    -I$(BREW_PREFIX)/include/libwebsockets \
    -I$(BREW_PREFIX)/include/jansson \
    -I$(BREW_PREFIX)/include/microhttpd \
    -I$(BREW_PREFIX)/include/SDL2
  LDFLAGS = -L$(BREW_PREFIX)/lib -lm -lwebsockets -ljansson -lmicrohttpd -lSDL2 -lSDL2_ttf -framework OpenGL
else ifeq ($(UNAME_S),Linux)
  PKG_CONFIG ?= pkg-config
  PC_CFLAGS := $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_ttf libwebsockets jansson libmicrohttpd 2>/dev/null)
  PC_LIBS := $(shell $(PKG_CONFIG) --libs sdl2 SDL2_ttf libwebsockets jansson libmicrohttpd 2>/dev/null)
  COMMON_CFLAGS = -Wall -Wextra $(NOISE_INCLUDES) $(PC_CFLAGS) -pthread
  LDFLAGS = $(PC_LIBS) -lm -lGL -pthread
else
  # Best-effort fallback (e.g. BSD): adjust PREFIX as needed
  PREFIX ?= /usr/local
  COMMON_CFLAGS = -Wall -Wextra $(NOISE_INCLUDES) \
    -I$(PREFIX)/include -I$(PREFIX)/include/SDL2 -pthread
  LDFLAGS = -L$(PREFIX)/lib -lm -lwebsockets -ljansson -lmicrohttpd -lSDL2 -lSDL2_ttf -lGL -pthread
endif

# GCC-specific flags
GCC_CFLAGS = $(COMMON_CFLAGS)

# Clang-specific flags
CLANG_CFLAGS = $(COMMON_CFLAGS) -Weverything -Wno-disabled-macro-expansion -Wno-padded \
               -Wno-covered-switch-default -Wno-reserved-id-macro -Wno-documentation \
               -Wno-documentation-unknown-command -Wno-missing-variable-declarations \
               -Wno-missing-prototypes -Wno-unused-macros -Wno-c++98-compat \
               -Wno-c++98-compat-pedantic -Wno-vla -Wno-vla-extension

# Header dependencies, generated by the compiler rather than written by hand.
#
# The rules below name their headers explicitly, and some of them are wrong or incomplete — which
# does not fail the build, it produces a binary. A test object compiled against one layout of a
# struct, linked against library objects compiled against another, gives failures nowhere near the
# change that caused them: src/test_spawn_gravity.o listed no headers at all, so adding a field to
# GameState left it reading the wrong offsets and ten unrelated gravity assertions failed. -MMD
# writes what each object really included and the -include below makes make honour it, so an
# incomplete rule can no longer produce a stale object.
DEPFLAGS = -MMD -MP

# Default flags
CFLAGS = $(GCC_CFLAGS) $(OPTFLAGS) $(DEPFLAGS)
UI_CFLAGS = $(CFLAGS) -DUI_BUILD -DINTERFACE_MODE

# Emscripten config (for WebAssembly builds)
EMCC ?= emcc
EMCFLAGS = -O2 -sALLOW_MEMORY_GROWTH=1 -sASSERTIONS=1 -sFORCE_FILESYSTEM=1 -sUSE_SDL=2 -sUSE_SDL_TTF=2

# Noise library
NOISE_LIB = src/noise-c/src/protocol/libnoiseprotocol.a \
            src/noise-c/src/protobufs/libnoiseprotobufs.a \
            src/noise-c/src/keys/libnoisekeys.a
SHA256_OBJ = src/noise-c/src/crypto/sha2/sha256.o

# Anything linking src/world.o needs this entire set, not just world.o: world.c
# calls into bulk ops, universe placement, entropy sampling and constants, and
# universe.c calls back into the entropy generator. Declared once so link lines
# cannot drift; the set is closed (verified with nm -u).
# gpu_voxel_buffer belongs here despite the name: it is plain C with no SDL or GL, and world.c
# builds the occupancy bitfield through it for the renderer's face culling.
WORLD_CORE_OBJS = src/world.o src/world_bulk_ops.o src/constants.o \
                  src/universe.o src/entropy_field.o src/universe_coords.o src/universe_biome.o \
                  src/settlement.o src/household.o src/chronicle.o src/adventure_hooks.o src/world_entropy_generator.o src/gpu_voxel_buffer.o \
                  src/particle_effects.o src/fire_sim.o src/fluid_sim.o src/fluid_surface.o src/water_erosion.o src/water_table.o src/fog_volume.o \
                  src/fog_of_war.o src/shadow_world.o src/task_scheduler.o src/volcano.o src/lightning_path.o src/weather_storm.o \
                  src/mob_ai.o src/actor.o src/character.o src/item.o src/mob_loot.o src/currency.o src/poly_mesh.o src/voxel_shape.o $(SHA256_OBJ)

# shadow_world.o and task_scheduler.o are in the group because fog_of_war.o is: revealing fog samples
# the shadow cluster, and the cluster search runs on the task pool. Leaving them out meant all forty
# targets that link the world core had to know that, and the ones that did not simply failed to link.
#
# THREAD_OBJS and CLIENT_LIB_OBJS name them too, so any link line that combines those with this group
# is wrapped in $(sort ...), which is how make spells "remove duplicates". Without it the same object
# appears on the command line twice, and that is a duplicate symbol rather than a no-op.

# Same set as translation units, for the Emscripten build which compiles from source.
WORLD_CORE_SRCS = src/world.c src/world_bulk_ops.c src/constants.c \
                  src/universe.c src/entropy_field.c src/universe_coords.c src/universe_biome.c \
                  src/settlement.c src/household.c src/chronicle.c src/adventure_hooks.c src/world_entropy_generator.c src/gpu_voxel_buffer.c \
                  src/particle_effects.c src/fire_sim.c src/fluid_sim.c src/fluid_surface.c src/water_erosion.c src/water_table.c src/fog_volume.c \
                  src/fog_of_war.c src/shadow_world.c src/task_scheduler.c src/volcano.c src/lightning_path.c src/weather_storm.c \
                  src/mob_ai.c src/actor.c src/character.c src/item.c src/mob_loot.c src/currency.c src/poly_mesh.c src/voxel_shape.c \
                  src/noise-c/src/crypto/sha2/sha256.c

# Sub-voxel rendering: material template worlds plus the SDL atlas built from them. Anything that
# links isometric_renderer.o needs both, because the renderer resolves face UVs through the atlas
# and the atlas bakes from the templates. fp_renderer.o needs only material_worlds.o, because it
# rasterises on the CPU and samples the bakes directly. material_worlds.o alone is plain C with no
# SDL, which is what lets test_material_worlds run headlessly.
SUBVOXEL_OBJS = src/material_worlds.o src/material_atlas.o src/foliage_bend.o

# Nested voxel models for mobs. mob_models.o is plain C (headless tests); mob_sprite.o is the
# SDL isometric bake and only links into the client.
MOB_MODEL_OBJS = src/mob_models.o
MOB_SPRITE_OBJS = src/mob_sprite.o

# Threading: the worker pool plus the jobs built on it. Kept out of WORLD_CORE_OBJS so the
# headless tools and tests, which never start a pool, do not have to link it. Anything that
# submits work needs the whole set, because the jobs call into the pool.
THREAD_OBJS = src/task_scheduler.o src/world_gen_job.o src/world_physics_jobs.o
# world_physics_jobs calls voxel_fracture_step_falling; keep the object next to combat.
FRACTURE_OBJS = src/voxel_fracture.o src/voxel_combat.o src/voxel_debris_volume.o

# The shadow world cluster: one queryable coordinate space over the 3x3x3 of worlds around the
# player, and the shared search layer built on it. Plain C over borrowed World pointers, so it links
# into headless tools too, but it lives with the threading objects because GameState drives its
# residency from the physics tick and streams worlds in through the cell generation job.
SHADOW_OBJS = src/shadow_world.o
THREAD_SRCS = src/task_scheduler.c src/world_gen_job.c src/world_physics_jobs.c

# Core engine sources (main server/client); world core comes from WORLD_CORE_OBJS
CORE_SOURCES = src/main.c src/server.c src/engine.c src/client.c \
               src/verse.c src/player.c src/mud_telnet.c
CORE_OBJECTS = $(CORE_SOURCES:.c=.o)

# Game client sources (UI-based game); world core comes from WORLD_CORE_OBJS.
# Split so tests can link the client's guts against their own main.
CLIENT_LIB_OBJS = src/game_state.o src/storyline.o src/dialogue.o src/adventure_hooks.o src/game_log.o src/skill.o src/player_controls.o src/shop.o src/craft.o src/projectile.o src/debris.o src/voxel_combat.o src/voxel_fracture.o src/voxel_debris_volume.o src/spirit_sprite.o src/item_icon.o src/window.o src/fp_renderer.o src/voxel_shape.o src/gl_occupancy.o src/voxel_mesh.o src/octree.o \
                src/nav_aide.o src/gamepad.o \
                src/character.o src/actor.o src/world_transition.o src/world_spawn.o \
                src/input_manager.o src/engine.o \
                src/sequencer/melody_loader.o src/background_music.o \
                src/synthesizer/synthesizer.o src/songwriter/songwriter.o \
                src/isometric_renderer.o src/fog_volume.o src/console.o src/settings.o src/ui_sounds.o src/game_sfx.o \
                src/model_transformer.o src/greedy_mesh.o src/title_hum.o \
                src/wfc.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(THREAD_OBJS) $(SHADOW_OBJS)

CLIENT_SOURCES = src/verse_client.o $(CLIENT_LIB_OBJS)

# Proxy sources; world core comes from WORLD_CORE_OBJS
PROXY_SOURCES = src/proxy.c src/engine.c
PROXY_OBJECTS = $(PROXY_SOURCES:.c=.o)

# Build targets
all: verse-client starfighter entropy-test universe-entropy-simple-test universe-entropy-test wilderness-slice-analyzer
# Universe map generator (outputs BMP layers into assets/)
universe-map: src/universe_map_generator.o $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o universe-map src/universe_map_generator.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Universe reference renderer (top-down reference image generator)
universe-ref: src/universe_reference.o src/isometric_renderer.o src/fp_renderer.o src/gl_occupancy.o src/voxel_mesh.o src/octree.o src/cpu_renderer_optimized.o src/sprite_renderer.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o universe-ref src/universe_reference.o src/isometric_renderer.o src/fp_renderer.o src/gl_occupancy.o src/voxel_mesh.o src/octree.o src/cpu_renderer_optimized.o src/sprite_renderer.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

# Asset converter utility
asset-converter: src/asset_converter.o src/model_transformer.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o asset-converter src/asset_converter.o src/model_transformer.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Main game client (the primary target)
verse-client: $(CLIENT_SOURCES) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o verse-client $(sort $(CLIENT_SOURCES) $(WORLD_CORE_OBJS)) $(LDFLAGS)

# Debug build and run under LLDB
.PHONY: debug
debug: CFLAGS += -g -O0
debug: verse-client
	@echo "Launching LLDB for verse-client (break at main)..."
	@lldb -f ./verse-client -o "break set -n main" -o run

# Core engine/server (traditional version)
verse: $(CORE_OBJECTS) src/wfc.o $(NOISE_LIB) $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o verse $(CORE_OBJECTS) src/wfc.o $(WORLD_CORE_OBJS) $(NOISE_LIB) $(LDFLAGS)

# Proxy server
proxy: $(PROXY_OBJECTS) src/wfc.o $(NOISE_LIB) $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o proxy $(PROXY_OBJECTS) src/wfc.o $(WORLD_CORE_OBJS) $(NOISE_LIB) $(LDFLAGS)

# Render test program
render-test: src/render_test.o src/isometric_renderer.o src/wfc.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o render-test src/render_test.o src/isometric_renderer.o src/wfc.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

# Layer viewer to inspect generated worlds slice-by-slice (Z vertical)
layer-viewer: src/layer_viewer.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o layer-viewer src/layer_viewer.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# World viewer for .vox imports
world-viewer: src/world_viewer.o src/model_transformer.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o world-viewer src/world_viewer.o src/model_transformer.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# World editor (GPU-backed with optimized CPU fallback)
world-editor: src/world_editor.o src/isometric_renderer.o src/cpu_renderer_optimized.o src/unified_renderer.o src/model_transformer.o src/fluid_navier_stokes.o src/wfc.o src/fp_renderer.o src/gl_occupancy.o src/octree.o src/voxel_mesh.o src/gpu_physics.o src/ui_system.o src/world_editor_ui.o src/world_editor_input.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) src/spirit_sprite.o src/item_icon.o $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o world-editor src/world_editor.o src/isometric_renderer.o src/cpu_renderer_optimized.o src/unified_renderer.o src/model_transformer.o src/fluid_navier_stokes.o src/wfc.o src/fp_renderer.o src/gl_occupancy.o src/octree.o src/voxel_mesh.o src/gpu_physics.o src/ui_system.o src/world_editor_ui.o src/world_editor_input.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) src/spirit_sprite.o src/item_icon.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Naive window performance test
naive-window: src/naive_window.o src/isometric_renderer.o src/fp_renderer.o src/gl_occupancy.o src/voxel_mesh.o src/octree.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o naive-window src/naive_window.o src/isometric_renderer.o src/fp_renderer.o src/gl_occupancy.o src/voxel_mesh.o src/octree.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

# Greedy mesh utility
greedy-mesh: src/greedy_mesh_main.o src/greedy_mesh.o src/model_transformer.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o greedy-mesh src/greedy_mesh_main.o src/greedy_mesh.o src/model_transformer.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# CPU renderer optimization benchmark
cpu-benchmark: src/cpu_renderer_benchmark.o src/cpu_renderer_optimized.o src/isometric_renderer.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o cpu-benchmark src/cpu_renderer_benchmark.o src/cpu_renderer_optimized.o src/isometric_renderer.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

# CPU render phases test tool
cpu-render-phases: src/cpu_render_phases_test.o src/cpu_renderer_optimized.o src/isometric_renderer.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o cpu-render-phases src/cpu_render_phases_test.o src/cpu_renderer_optimized.o src/isometric_renderer.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

# Entropy field system test
entropy-test: src/entropy_test_minimal.o src/entropy_field.o src/universe_coords.o $(SHA256_OBJ)
	$(CC) $(UI_CFLAGS) -o entropy-test src/entropy_test_minimal.o src/entropy_field.o src/universe_coords.o $(SHA256_OBJ) $(LDFLAGS)

# Simple universe entropy field system test
universe-entropy-simple-test: src/universe_entropy_simple_test.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o universe-entropy-simple-test src/universe_entropy_simple_test.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Full universe entropy field system test
universe-entropy-test: src/universe_entropy_test.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o universe-entropy-test src/universe_entropy_test.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Wilderness slice analyzer for edge detection
wilderness-slice-analyzer: src/wilderness_slice_analyzer.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o wilderness-slice-analyzer src/wilderness_slice_analyzer.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Clang builds
clang: CFLAGS = $(CLANG_CFLAGS)
clang: CC = $(CLANG)
clang: verse-client

clang-verse: CFLAGS = $(CLANG_CFLAGS)
clang-verse: CC = $(CLANG)
clang-verse: verse

# Object file rules
src/verse_client.o: src/verse_client.c
	$(CC) $(UI_CFLAGS) -c src/verse_client.c -o src/verse_client.o

src/game_state.o: src/game_state.c
	$(CC) $(UI_CFLAGS) -c src/game_state.c -o src/game_state.o

src/storyline.o: src/storyline.c
	$(CC) $(UI_CFLAGS) -c src/storyline.c -o src/storyline.o

src/dialogue.o: src/dialogue.c src/dialogue.h
	$(CC) $(UI_CFLAGS) -c src/dialogue.c -o src/dialogue.o

src/skill.o: src/skill.c src/skill.h
	$(CC) $(UI_CFLAGS) -c src/skill.c -o src/skill.o

src/player_controls.o: src/player_controls.c
	$(CC) $(UI_CFLAGS) -c src/player_controls.c -o src/player_controls.o

src/gamepad.o: src/gamepad.c src/gamepad.h
	$(CC) $(UI_CFLAGS) -c src/gamepad.c -o src/gamepad.o

src/projectile.o: src/projectile.c src/projectile.h
	$(CC) $(UI_CFLAGS) -c src/projectile.c -o src/projectile.o

src/debris.o: src/debris.c src/debris.h src/voxel_combat.h
	$(CC) $(UI_CFLAGS) -c src/debris.c -o src/debris.o

src/voxel_combat.o: src/voxel_combat.c src/voxel_combat.h
	$(CC) $(UI_CFLAGS) -c src/voxel_combat.c -o src/voxel_combat.o

src/voxel_fracture.o: src/voxel_fracture.c src/voxel_fracture.h src/voxel_combat.h src/voxel_debris_volume.h
	$(CC) $(CFLAGS) -c src/voxel_fracture.c -o src/voxel_fracture.o

src/voxel_debris_volume.o: src/voxel_debris_volume.c src/voxel_debris_volume.h src/voxel_fracture.h
	$(CC) $(CFLAGS) -c src/voxel_debris_volume.c -o src/voxel_debris_volume.o

src/spirit_sprite.o: src/spirit_sprite.c
	$(CC) $(UI_CFLAGS) -c src/spirit_sprite.c -o src/spirit_sprite.o

src/item_icon.o: src/item_icon.c src/item_icon.h src/item_icon_data.inc src/item.h
	$(CC) $(UI_CFLAGS) -c src/item_icon.c -o src/item_icon.o

src/window.o: src/window.c
	$(CC) $(UI_CFLAGS) -c src/window.c -o src/window.o

src/world.o: src/world.c
	$(CC) $(UI_CFLAGS) -c src/world.c -o src/world.o

src/character.o: src/character.c
	$(CC) $(UI_CFLAGS) -c src/character.c -o src/character.o

src/actor.o: src/actor.c
	$(CC) $(UI_CFLAGS) -c src/actor.c -o src/actor.o

src/item.o: src/item.c src/item.h
	$(CC) $(CFLAGS) -c src/item.c -o src/item.o

src/currency.o: src/currency.c src/currency.h
	$(CC) $(CFLAGS) -c src/currency.c -o src/currency.o

src/shop.o: src/shop.c src/shop.h src/currency.h src/item.h src/game_state.h
	$(CC) $(UI_CFLAGS) -c src/shop.c -o src/shop.o
src/craft.o: src/craft.c src/craft.h src/item.h src/voxel.h src/world.h
	$(CC) $(CFLAGS) -c src/craft.c -o src/craft.o

src/mob_loot.o: src/mob_loot.c src/mob_loot.h src/item.h src/mob_ai.h
	$(CC) $(CFLAGS) -c src/mob_loot.c -o src/mob_loot.o

src/world_transition.o: src/world_transition.c
	$(CC) $(UI_CFLAGS) -c src/world_transition.c -o src/world_transition.o

src/world_spawn.o: src/world_spawn.c
	$(CC) $(UI_CFLAGS) -c src/world_spawn.c -o src/world_spawn.o

src/input_manager.o: src/input_manager.c
	$(CC) $(UI_CFLAGS) -c src/input_manager.c -o src/input_manager.o

src/engine.o: src/engine.c
	$(CC) $(UI_CFLAGS) -c src/engine.c -o src/engine.o

src/isometric_renderer.o: src/isometric_renderer.c
	$(CC) $(UI_CFLAGS) -c src/isometric_renderer.c -o src/isometric_renderer.o

# Optimized CPU renderer
src/cpu_renderer_optimized.o: src/cpu_renderer_optimized.c src/cpu_renderer_optimized.h src/chunk_config.h
	$(CC) $(UI_CFLAGS) -c src/cpu_renderer_optimized.c -o src/cpu_renderer_optimized.o

# Unified renderer interface
src/unified_renderer.o: src/unified_renderer.c src/unified_renderer.h src/cpu_renderer_optimized.h
	$(CC) $(UI_CFLAGS) -c src/unified_renderer.c -o src/unified_renderer.o

# CPU renderer benchmark
src/cpu_renderer_benchmark.o: src/cpu_renderer_benchmark.c src/cpu_renderer_optimized.h src/isometric_renderer.h
	$(CC) $(UI_CFLAGS) -c src/cpu_renderer_benchmark.c -o src/cpu_renderer_benchmark.o

src/gpu_voxel_buffer.o: src/gpu_voxel_buffer.c src/gpu_voxel_buffer.h src/world.h
	$(CC) $(CFLAGS) -c src/gpu_voxel_buffer.c -o src/gpu_voxel_buffer.o

src/gl_occupancy.o: src/gl_occupancy.c src/gl_occupancy.h src/gpu_voxel_buffer.h
	$(CC) $(UI_CFLAGS) -c src/gl_occupancy.c -o src/gl_occupancy.o

src/fluid_navier_stokes.o: src/fluid_navier_stokes.c src/fluid_navier_stokes.h src/world.h
	$(CC) $(UI_CFLAGS) -c src/fluid_navier_stokes.c -o src/fluid_navier_stokes.o

src/model_transformer.o: src/model_transformer.c src/model_transformer.h src/world.h
	$(CC) $(UI_CFLAGS) -c src/model_transformer.c -o src/model_transformer.o

src/greedy_mesh.o: src/greedy_mesh.c src/greedy_mesh.h src/world.h
	$(CC) $(CFLAGS) -c src/greedy_mesh.c -o src/greedy_mesh.o

src/greedy_mesh_main.o: src/greedy_mesh_main.c src/greedy_mesh.h src/model_transformer.h src/world.h
	$(CC) $(CFLAGS) -c src/greedy_mesh_main.c -o src/greedy_mesh_main.o

src/constants.o: src/constants.c src/constants.h
	$(CC) $(CFLAGS) -c src/constants.c -o src/constants.o

src/universe.o: src/universe.c src/universe.h src/world.h
	$(CC) $(CFLAGS) -c src/universe.c -o src/universe.o

src/settings.o: src/settings.c src/settings.h
	$(CC) $(UI_CFLAGS) -c src/settings.c -o src/settings.o

src/ui_sounds.o: src/ui_sounds.c src/ui_sounds.h
	$(CC) $(UI_CFLAGS) -c src/ui_sounds.c -o src/ui_sounds.o

src/game_sfx.o: src/game_sfx.c src/game_sfx.h src/synthesizer/synthesizer.h
	$(CC) $(UI_CFLAGS) -c src/game_sfx.c -o src/game_sfx.o

# Octree
src/octree.o: src/octree.c src/octree.h src/world.h
	$(CC) $(UI_CFLAGS) -c src/octree.c -o src/octree.o

# Voxel mesh
src/voxel_mesh.o: src/voxel_mesh.c src/voxel_mesh.h src/world.h
	$(CC) $(UI_CFLAGS) -c src/voxel_mesh.c -o src/voxel_mesh.o

# Title hum
src/title_hum.o: src/title_hum.c src/title_hum.h src/synthesizer/synthesizer.h
	$(CC) $(UI_CFLAGS) -c src/title_hum.c -o src/title_hum.o

src/render_test.o: src/render_test.c
	$(CC) $(UI_CFLAGS) -c src/render_test.c -o src/render_test.o

src/universe_map_generator.o: src/universe_map_generator.c
	$(CC) $(UI_CFLAGS) -c src/universe_map_generator.c -o src/universe_map_generator.o

src/layer_viewer.o: src/layer_viewer.c
	$(CC) $(UI_CFLAGS) -c src/layer_viewer.c -o src/layer_viewer.o

src/world_viewer.o: src/world_viewer.c src/model_transformer.h src/world.h
	$(CC) $(UI_CFLAGS) -c src/world_viewer.c -o src/world_viewer.o

src/fp_renderer.o: src/fp_renderer.c src/fp_renderer.h src/world.h src/isometric_renderer.h src/material_worlds.h src/mob_models.h src/poly_mesh.h
	$(CC) $(UI_CFLAGS) -c src/fp_renderer.c -o src/fp_renderer.o

src/world_editor.o: src/world_editor.c src/model_transformer.h src/world.h src/isometric_renderer.h
	$(CC) $(UI_CFLAGS) -c src/world_editor.c -o src/world_editor.o

src/gpu_physics.o: src/gpu_physics.c src/gpu_physics.h src/world.h
	$(CC) $(UI_CFLAGS) -c src/gpu_physics.c -o src/gpu_physics.o

src/asset_converter.o: src/asset_converter.c src/model_transformer.h src/world.h
	$(CC) $(CFLAGS) -c src/asset_converter.c -o src/asset_converter.o

src/starfighter.o: src/starfighter.c src/constants.h
	$(CC) $(UI_CFLAGS) -c src/starfighter.c -o src/starfighter.o

# World tool (batch operations on .world files)
world-tool: src/world_tool.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o world-tool src/world_tool.o src/wfc.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Starfighter space combat game
starfighter: src/starfighter.o src/constants.o
	$(CC) $(UI_CFLAGS) -o starfighter src/starfighter.o src/constants.o $(LDFLAGS)

src/sequencer/melody_loader.o: src/sequencer/melody_loader.c
	$(CC) $(CFLAGS) -c src/sequencer/melody_loader.c -o src/sequencer/melody_loader.o

src/background_music.o: src/background_music.c
	$(CC) $(CFLAGS) -c src/background_music.c -o src/background_music.o

src/synthesizer/synthesizer.o: src/synthesizer/synthesizer.c
	$(CC) $(CFLAGS) -c src/synthesizer/synthesizer.c -o src/synthesizer/synthesizer.o

src/songwriter/songwriter.o: src/songwriter/songwriter.c
	$(CC) $(CFLAGS) -c src/songwriter/songwriter.c -o src/songwriter/songwriter.o

$(SHA256_OBJ): src/noise-c/src/crypto/sha2/sha256.c
	$(CC) $(CFLAGS) -c src/noise-c/src/crypto/sha2/sha256.c -o $(SHA256_OBJ)

# Core engine objects (for traditional verse build)
src/main.o: src/main.c
	$(CC) $(CFLAGS) -c src/main.c -o src/main.o

# No -DMAIN_SERVER: that guard exists to build server.c as a standalone binary, and
# defining it here gave server.o its own main(), colliding with main.o inside `verse`.
src/server.o: src/server.c
	$(CC) $(CFLAGS) -c src/server.c -o src/server.o

src/client.o: src/client.c
	$(CC) $(CFLAGS) -c src/client.c -o src/client.o

src/verse.o: src/verse.c
	$(CC) $(CFLAGS) -c src/verse.c -o src/verse.o

src/player.o: src/player.c
	$(CC) $(CFLAGS) -c src/player.c -o src/player.o

src/proxy.o: src/proxy.c
	$(CC) $(CFLAGS) -c src/proxy.c -o src/proxy.o

# Noise protocol library
$(NOISE_LIB):
	cd src/noise-c && make

# Production verification: native client + headless C checks (no npm).
# Every suite here reports failures through its exit code, so `make` aborts the gate
# on the first one that fails. Only self-contained suites belong here: nothing that
# depends on pre-existing fixtures under worlds/, which is not checked in.
.PHONY: release-check-native
release-check-native: test-bulk-ops test-universe-consistency test-refactored-worlds \
                      test-home-island-shape test-world-roundtrip test-task-scheduler \
                      test-spawn-gravity test-foliage-projectiles \
                      test-movement-audit test-game-save-load \
                      test-universe-layout test-settlement test-currency test-craft test-chronicle test-nav-aide test-voxel-materials test-mob-skills \
                      test-material-worlds test-foliage-bend test-fog-volume test-mob-models test-poly-mesh test-shadow-world test-fog-of-war \
                      test-universe-biome test-fire-sim test-water-table test-volcano-storm \
                      test-storyline-playthrough \
                      entropy-test \
                      universe-entropy-simple-test universe-entropy-test \
                      test-fp-renderer test-mouse-look
	@echo "=== release-check-native: running headless C tests ==="
	./test-bulk-ops
	./test-universe-consistency
	./test-refactored-worlds
	./test-home-island-shape
	./test-world-roundtrip
	./test-task-scheduler
	./test-spawn-gravity
	./test-foliage-projectiles
	./test-movement-audit
	./test-game-save-load
	./test-universe-layout
	./test-settlement
	./test-currency
	./test-craft
	./test-chronicle
	./test-nav-aide
	./test-mob-skills
	./test-material-worlds
	./test-foliage-bend
	./test-fog-volume
	./test-mob-models
	./test-poly-mesh
	./test-shadow-world
	./test-fog-of-war
	./test-universe-biome
	./test-fire-sim
	./test-water-table
	./test-volcano-storm
	./test-storyline-playthrough
	./entropy-test
	./universe-entropy-simple-test
	./universe-entropy-test
	./test-mouse-look
	SDL_VIDEODRIVER=dummy ./test-fp-renderer
	$(MAKE) verse-client
	@echo "=== release-check-native: OK ==="

# Utility targets
clean:
	rm -f src/*.o src/*/*.o src/*.d src/*/*.d verse verse-client proxy starfighter render-test layer-viewer world-generation-benchmark world-analysis test-bulk-ops test-universe-consistency test-refactored-worlds test-home-island-shape
	rm -f test-*
	cd src/noise-c && make clean

clean-noise:
	cd src/noise-c && make clean

help:
	@echo "Available targets:"
	@echo "  verse-client  - Main game with UI (default)"
	@echo "  verse         - Core engine/server"
	@echo "  proxy         - Proxy server"
	@echo "  starfighter   - Space combat game with OpenGL rendering"
	@echo "  render-test   - Test program for rendering system"
	@echo "  layer-viewer  - Slice viewer for generated worlds (PageUp/PageDown to change Z)"
	@echo "  wasm          - Build WebAssembly viewer into assets/ (requires emscripten)"
	@echo "  clang         - Build verse-client with clang"
	@echo "  clang-verse   - Build verse with clang"
	@echo "  world-generation-benchmark - Build world generation benchmark suite"
	@echo "  world-analysis - Build world composition analysis program"
	@echo "  run-benchmark - Build and run world generation benchmarks"
	@echo "  test-bulk-ops - Build world bulk operations test suite"
	@echo "  run-bulk-ops-test - Build and run bulk operations tests"
	@echo "  test-universe-consistency - Build universe consistency test suite"
	@echo "  run-universe-consistency-test - Build and run universe consistency tests"
	@echo "  test-refactored-worlds - Build refactored world generation test suite"
	@echo "  run-refactored-worlds-test - Build and run refactored world generation tests"
	@echo "  test-home-island-shape - Build HOME world island shape visualization test"
	@echo "  run-home-island-shape-test - Build and run HOME world island shape test"
	@echo "  clean         - Clean all build artifacts"
	@echo "  help          - Show this help"
	@echo "  android-debug - Build Android APK (Debug) via Gradle"
	@echo "  android-release - Build Android APK (Release) via Gradle"
	@echo "  release-check-native - Headless C tests + verse-client build"

.PHONY: all clean clean-noise help clang clang-verse wasm wasm-clean starfighter release-check-native

# Last, so the generated rules add to the prerequisites the explicit rules above already declare.
# Absent on a first build, which is correct: nothing is stale when nothing has been built.
-include $(wildcard src/*.d src/*/*.d)

# -------------------------
# WebAssembly build (viewer)
# -------------------------

# Minimal SDL2/TTF viewer for browser. Outputs JS+WASM into assets/ and preloads assets/ directory.
wasm: assets/world_viewer.js

assets/world_viewer.js: src/world_viewer.c src/model_transformer.c src/greedy_mesh.c src/wfc.c $(WORLD_CORE_SRCS)
	$(EMCC) $(CFLAGS) $(EMCFLAGS) \
	  src/world_viewer.c src/model_transformer.c src/greedy_mesh.c src/wfc.c $(WORLD_CORE_SRCS) \
	  -o assets/world_viewer.js \
	  --preload-file assets/fonts@/assets/fonts

wasm-clean:
	rm -f assets/world_viewer.js assets/world_viewer.wasm assets/world_viewer.data

# Universe generator for gameworld stack (CLI-only, no SDL)
universe-generate-gameworld: src/universe_generate_gameworld.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o universe-generate-gameworld src/universe_generate_gameworld.o $(WORLD_CORE_OBJS) -lm

# Test program for Y-up coordinate transformation
test-yup-export: test_yup_export.o src/voxel_mesh.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-yup-export test_yup_export.o src/voxel_mesh.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Test program for HOME world generation and Y-up export
test-home-world: test_home_world.o src/voxel_mesh.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-home-world test_home_world.o src/voxel_mesh.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# Test program for enhanced world loading functionality
test-load-world: test_load_world.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-load-world test_load_world.o $(WORLD_CORE_OBJS) $(LDFLAGS)

# World generation benchmark suite
world-generation-benchmark: src/world_generation_benchmark.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o world-generation-benchmark src/world_generation_benchmark.o $(WORLD_CORE_OBJS) -lm

# World composition analysis program
world-analysis: src/world_analysis.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o world-analysis src/world_analysis.o $(WORLD_CORE_OBJS) -lm

# World Editor renderer benchmark
src/world_editor_renderer_benchmark.o: src/world_editor_renderer_benchmark.c
	$(CC) $(UI_CFLAGS) -c -o src/world_editor_renderer_benchmark.o src/world_editor_renderer_benchmark.c

world-editor-renderer-benchmark: src/world_editor_renderer_benchmark.o src/unified_renderer.o src/isometric_renderer.o src/cpu_renderer_optimized.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o world-editor-renderer-benchmark src/world_editor_renderer_benchmark.o src/unified_renderer.o src/isometric_renderer.o src/cpu_renderer_optimized.o $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

run-benchmark: world-generation-benchmark
	./world-generation-benchmark

# Permanent performance benchmark, covering the voxel access floor, generation, physics and the
# real isometric render scan. Links the isometric renderer, so it needs the UI flags, but runs
# headless: the functions it measures build CPU-side buffers and never touch a window.
src/verse_benchmark.o: src/verse_benchmark.c src/isometric_renderer.h src/world.h src/world_spawn.h
	$(CC) $(UI_CFLAGS) -c -o src/verse_benchmark.o src/verse_benchmark.c

verse-benchmark: src/verse_benchmark.o src/isometric_renderer.o src/world_spawn.o src/wfc.o \
                 src/greedy_mesh.o src/spirit_sprite.o src/item_icon.o $(FRACTURE_OBJS) \
                 $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o verse-benchmark src/verse_benchmark.o src/isometric_renderer.o \
	  src/world_spawn.o src/wfc.o src/greedy_mesh.o src/spirit_sprite.o src/item_icon.o $(FRACTURE_OBJS) \
	  $(SUBVOXEL_OBJS) $(MOB_MODEL_OBJS) $(MOB_SPRITE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

run-verse-benchmark: verse-benchmark
	./verse-benchmark

# FP material-worlds gameplay framerate bench: init/bake, sparse mesh extract, parent remesh,
# and 256x240 mesh frames (lawn / bush grove / fittings / home) with sparse silhouette timing.
src/material_fp_benchmark.o: src/material_fp_benchmark.c src/fp_renderer.h src/material_worlds.h \
                             src/voxel_mesh.h
	$(CC) $(UI_CFLAGS) -c -o src/material_fp_benchmark.o src/material_fp_benchmark.c

material-fp-benchmark: src/material_fp_benchmark.o src/fp_renderer.o src/gl_occupancy.o \
                       src/voxel_mesh.o src/octree.o src/material_worlds.o src/mob_models.o \
                       src/foliage_bend.o $(FRACTURE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o material-fp-benchmark src/material_fp_benchmark.o src/fp_renderer.o \
	  src/gl_occupancy.o src/voxel_mesh.o src/octree.o src/material_worlds.o src/mob_models.o \
	  src/foliage_bend.o $(FRACTURE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

run-material-fp-benchmark: material-fp-benchmark
	./material-fp-benchmark

# Sub-voxel material template worlds. Plain C over the world core, so the tests are headless.
src/material_worlds.o: src/material_worlds.c src/material_worlds.h src/world.h src/voxel.h
	$(CC) $(CFLAGS) -c src/material_worlds.c -o src/material_worlds.o

src/foliage_bend.o: src/foliage_bend.c src/foliage_bend.h src/voxel.h src/world.h
	$(CC) $(CFLAGS) -c src/foliage_bend.c -o src/foliage_bend.o

# The atlas is the one piece of the sub-voxel path that needs SDL, hence UI flags.
src/material_atlas.o: src/material_atlas.c src/material_atlas.h src/material_worlds.h
	$(CC) $(UI_CFLAGS) -c src/material_atlas.c -o src/material_atlas.o

test-material-worlds: src/test_material_worlds.o src/material_worlds.o src/voxel_mesh.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-material-worlds src/test_material_worlds.o src/material_worlds.o \
	  src/voxel_mesh.o $(WORLD_CORE_OBJS) -lm

run-material-worlds-test: test-material-worlds
	./test-material-worlds

test-foliage-bend: src/test_foliage_bend.o src/foliage_bend.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-foliage-bend src/test_foliage_bend.o src/foliage_bend.o \
	  $(WORLD_CORE_OBJS) -lm

run-foliage-bend-test: test-foliage-bend
	./test-foliage-bend

src/poly_mesh.o: src/poly_mesh.c src/poly_mesh.h
	$(CC) $(CFLAGS) -c src/poly_mesh.c -o src/poly_mesh.o

test-poly-mesh: src/test_poly_mesh.o src/poly_mesh.o
	$(CC) $(CFLAGS) -o test-poly-mesh src/test_poly_mesh.o src/poly_mesh.o -lm

run-poly-mesh-test: test-poly-mesh
	./test-poly-mesh

src/mob_models.o: src/mob_models.c src/mob_models.h src/world.h src/actor.h src/mob_ai.h
	$(CC) $(CFLAGS) -c src/mob_models.c -o src/mob_models.o

src/mob_sprite.o: src/mob_sprite.c src/mob_sprite.h src/mob_models.h
	$(CC) $(UI_CFLAGS) -c src/mob_sprite.c -o src/mob_sprite.o

test-mob-models: src/test_mob_models.o src/mob_models.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-mob-models src/test_mob_models.o src/mob_models.o \
	  $(WORLD_CORE_OBJS) -lm

run-mob-models-test: test-mob-models
	./test-mob-models

test-universe-biome: src/test_universe_biome.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-universe-biome src/test_universe_biome.o \
	  $(WORLD_CORE_OBJS) -lm

run-universe-biome-test: test-universe-biome
	./test-universe-biome

# Fluid simulation and the sub-voxel surface field it drives. Both are plain C over the world core
# — no SDL — so the physics and the wave field can be tested headlessly.
src/fluid_sim.o: src/fluid_sim.c src/fluid_sim.h src/water_erosion.h src/world.h src/voxel.h
	$(CC) $(CFLAGS) -c src/fluid_sim.c -o src/fluid_sim.o

src/water_erosion.o: src/water_erosion.c src/water_erosion.h src/fluid_sim.h src/universe_biome.h src/world.h src/voxel.h
	$(CC) $(CFLAGS) -c src/water_erosion.c -o src/water_erosion.o

src/fluid_surface.o: src/fluid_surface.c src/fluid_surface.h src/fluid_sim.h src/world.h src/voxel.h
	$(CC) $(CFLAGS) -c src/fluid_surface.c -o src/fluid_surface.o

src/fog_volume.o: src/fog_volume.c src/fog_volume.h src/world.h
	$(CC) $(CFLAGS) -c src/fog_volume.c -o src/fog_volume.o

test-fluid-sim: src/test_fluid_sim.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-fluid-sim src/test_fluid_sim.o $(WORLD_CORE_OBJS) -lm

run-fluid-sim-test: test-fluid-sim
	./test-fluid-sim

test-water-table: src/test_water_table.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-water-table src/test_water_table.o $(WORLD_CORE_OBJS) -lm

test-volcano-storm: src/test_volcano_storm.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-volcano-storm src/test_volcano_storm.o $(WORLD_CORE_OBJS) -lm

run-volcano-storm-test: test-volcano-storm
	./test-volcano-storm


run-water-table-test: test-water-table
	./test-water-table

test-fire-sim: src/test_fire_sim.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-fire-sim src/test_fire_sim.o $(WORLD_CORE_OBJS) -lm

run-fire-sim-test: test-fire-sim
	./test-fire-sim

test-fog-volume: src/test_fog_volume.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-fog-volume src/test_fog_volume.o $(WORLD_CORE_OBJS) -lm

run-fog-volume-test: test-fog-volume
	./test-fog-volume

# Shadow world cluster: the 3x3x3 query space and its shared search layer. Plain C over borrowed
# World pointers, so it runs headlessly; task_scheduler comes along for the parallel fan-out.
src/shadow_world.o: src/shadow_world.c src/shadow_world.h src/world.h src/gpu_voxel_buffer.h
	$(CC) $(CFLAGS) -c src/shadow_world.c -o src/shadow_world.o

test-shadow-world: src/test_shadow_world.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-shadow-world src/test_shadow_world.o $(WORLD_CORE_OBJS) -lm

run-shadow-world-test: test-shadow-world
	./test-shadow-world

test-fog-of-war: src/test_fog_of_war.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-fog-of-war src/test_fog_of_war.o $(WORLD_CORE_OBJS) -lm

run-fog-of-war-test: test-fog-of-war
	./test-fog-of-war

# First-person renderer audit: quad planarity, projection/ray inverse, rendered frame statistics.
# Needs UI flags and SDL because it renders a real frame through a software renderer.
src/fp_renderer_audit_test.o: src/fp_renderer_audit_test.c src/fp_renderer.h src/voxel_mesh.h
	$(CC) $(UI_CFLAGS) -c src/fp_renderer_audit_test.c -o src/fp_renderer_audit_test.o

test-fp-renderer: src/fp_renderer_audit_test.o src/fp_renderer.o src/gl_occupancy.o src/voxel_mesh.o src/octree.o src/material_worlds.o src/mob_models.o src/foliage_bend.o $(FRACTURE_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-fp-renderer src/fp_renderer_audit_test.o src/fp_renderer.o src/gl_occupancy.o \
	  src/voxel_mesh.o src/octree.o src/material_worlds.o src/mob_models.o src/foliage_bend.o \
	  $(FRACTURE_OBJS) $(WORLD_CORE_OBJS) $(LDFLAGS)

run-fp-renderer-test: test-fp-renderer
	./test-fp-renderer

# Mouse look: asserts view rotation stays bound by the player's turn speed.
src/mouse_look_test.o: src/mouse_look_test.c src/player_controls.h src/player_controls_types.h
	$(CC) $(UI_CFLAGS) -c src/mouse_look_test.c -o src/mouse_look_test.o

test-mouse-look: src/mouse_look_test.o $(CLIENT_LIB_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-mouse-look src/mouse_look_test.o \
	  $(sort $(CLIENT_LIB_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-mouse-look-test: test-mouse-look
	./test-mouse-look

# World bulk operations test suite
test-bulk-ops: src/test_bulk_ops.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-bulk-ops src/test_bulk_ops.o $(WORLD_CORE_OBJS) -lm

run-bulk-ops-test: test-bulk-ops
	./test-bulk-ops

# Universe consistency test suite
test-universe-consistency: src/test_universe_consistency.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-universe-consistency src/test_universe_consistency.o src/wfc.o $(WORLD_CORE_OBJS) -lm

run-universe-consistency-test: test-universe-consistency
	./test-universe-consistency

# Refactored world generation test suite
test-refactored-worlds: src/test_refactored_worlds.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-refactored-worlds src/test_refactored_worlds.o src/wfc.o $(WORLD_CORE_OBJS) -lm

run-refactored-worlds-test: test-refactored-worlds
	./test-refactored-worlds

# HOME world island shape test
src/test_home_island_shape.o: src/test_home_island_shape.c
	$(CC) $(CFLAGS) -c -o src/test_home_island_shape.o src/test_home_island_shape.c

test-home-island-shape: src/test_home_island_shape.o src/wfc.o src/world_spawn.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-home-island-shape src/test_home_island_shape.o src/wfc.o src/world_spawn.o $(WORLD_CORE_OBJS) -lm

run-home-island-shape-test: test-home-island-shape
	./test-home-island-shape

# World generation profiler. Built as its own object set with -DWORLD_GEN_PROFILE so the
# instrumentation exists only here; every other target compiles the same sources with the
# macros expanded to nothing.
PROFILE_DIR = build/profile
PROFILE_SRCS = $(WORLD_CORE_SRCS) src/wfc.c src/world_gen_profile.c src/world_generation_profile.c
PROFILE_OBJS = $(patsubst %.c,$(PROFILE_DIR)/%.o,$(PROFILE_SRCS))

$(PROFILE_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -DWORLD_GEN_PROFILE -c -o $@ $<

# What a new game costs through the real job path: the startup worlds the loading screen waits for,
# and the background ring generated right after. Keeping this a build target rather than a throwaway
# script is what makes the ring's cost visible when someone changes its radius.
world-gen-startup-profile: src/world_gen_startup_profile.o src/world_gen_job.o src/wfc.o \
                           $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o world-gen-startup-profile $(sort src/world_gen_startup_profile.o \
	  src/world_gen_job.o src/wfc.o $(WORLD_CORE_OBJS)) -lm

src/world_gen_startup_profile.o: src/world_gen_startup_profile.c
	$(CC) $(CFLAGS) -c src/world_gen_startup_profile.c -o src/world_gen_startup_profile.o

world-generation-profile: $(PROFILE_OBJS)
	$(CC) $(CFLAGS) -DWORLD_GEN_PROFILE -o world-generation-profile $(PROFILE_OBJS) -lm

run-world-generation-profile: world-generation-profile
	./world-generation-profile

src/test_world_roundtrip.o: src/test_world_roundtrip.c
	$(CC) $(CFLAGS) -c -o src/test_world_roundtrip.o src/test_world_roundtrip.c

test-world-roundtrip: src/test_world_roundtrip.o src/wfc.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-world-roundtrip src/test_world_roundtrip.o src/wfc.o $(WORLD_CORE_OBJS) -lm

run-world-roundtrip-test: test-world-roundtrip
	./test-world-roundtrip

src/test_task_scheduler.o: src/test_task_scheduler.c
	$(CC) $(CFLAGS) -c -o src/test_task_scheduler.o src/test_task_scheduler.c

test-task-scheduler: src/test_task_scheduler.o src/wfc.o $(THREAD_OBJS) $(FRACTURE_OBJS) src/material_worlds.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-task-scheduler src/test_task_scheduler.o src/wfc.o \
	  $(sort $(THREAD_OBJS) $(FRACTURE_OBJS) src/material_worlds.o $(WORLD_CORE_OBJS)) -lm

run-task-scheduler-test: test-task-scheduler
	./test-task-scheduler

# Drives the real spawn and gravity code, so it needs the client objects minus the client's
# own main().
SPAWN_GRAVITY_OBJS = $(filter-out src/verse_client.o,$(CLIENT_SOURCES))

src/test_spawn_gravity.o: src/test_spawn_gravity.c
	$(CC) $(UI_CFLAGS) -c -o src/test_spawn_gravity.o src/test_spawn_gravity.c

test-spawn-gravity: src/test_spawn_gravity.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-spawn-gravity src/test_spawn_gravity.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-spawn-gravity-test: test-spawn-gravity
	./test-spawn-gravity

# Foliage passability, projectile flight and the fireball skill. Same object set as the spawn and
# gravity test: it drives the real collision and skill code, so it needs the client minus its main().
src/test_foliage_projectiles.o: src/test_foliage_projectiles.c
	$(CC) $(UI_CFLAGS) -c -o src/test_foliage_projectiles.o src/test_foliage_projectiles.c

test-foliage-projectiles: src/test_foliage_projectiles.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-foliage-projectiles src/test_foliage_projectiles.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-foliage-projectiles-test: test-foliage-projectiles
	./test-foliage-projectiles

# The universe's layout and the fall between its layers. Same object set again: the fall runs through
# the client's real gravity and world-transition code.
src/test_universe_layout.o: src/test_universe_layout.c
	$(CC) $(UI_CFLAGS) -c -o src/test_universe_layout.o src/test_universe_layout.c

test-universe-layout: src/test_universe_layout.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-universe-layout src/test_universe_layout.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-universe-layout-test: test-universe-layout
	./test-universe-layout

# Settlement scale selection (0..9) and basic building stamps on the wilderness plane.
src/test_settlement.o: src/test_settlement.c
	$(CC) $(CFLAGS) -c -o src/test_settlement.o src/test_settlement.c

test-settlement: src/test_settlement.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-settlement src/test_settlement.o $(WORLD_CORE_OBJS) -lm

run-settlement-test: test-settlement
	./test-settlement

# Shape × orientation modifiers (wedge/slab/corner without new VoxelTypes).
src/test_voxel_shape.o: src/test_voxel_shape.c
	$(CC) $(CFLAGS) -c -o src/test_voxel_shape.o src/test_voxel_shape.c

test-voxel-shape: src/test_voxel_shape.o src/voxel_mesh.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-voxel-shape src/test_voxel_shape.o src/voxel_mesh.o $(WORLD_CORE_OBJS) -lm

run-voxel-shape-test: test-voxel-shape
	./test-voxel-shape

# Copper / silver / gold wallet + item buy/sell prices.
src/test_currency.o: src/test_currency.c
	$(CC) $(CFLAGS) -c -o src/test_currency.o src/test_currency.c

test-currency: src/test_currency.o src/currency.o src/item.o
	$(CC) $(CFLAGS) -o test-currency test-craft src/test_currency.o src/currency.o src/item.o -lm

run-currency-test: test-currency
	./test-currency

src/test_craft.o: src/test_craft.c
	$(CC) $(CFLAGS) -c -o src/test_craft.o src/test_craft.c

test-craft: src/test_craft.o src/craft.o src/item.o
	$(CC) $(CFLAGS) -o test-craft src/test_craft.o src/craft.o src/item.o -lm

run-craft-test: test-craft
	./test-craft


# Chronicle determinism, household registry, dialogue graph, adventure hooks.
src/test_chronicle.o: src/test_chronicle.c
	$(CC) $(CFLAGS) -c -o src/test_chronicle.o src/test_chronicle.c

test-chronicle: src/test_chronicle.o src/dialogue.o $(WORLD_CORE_OBJS)
	$(CC) $(CFLAGS) -o test-chronicle src/test_chronicle.o src/dialogue.o $(WORLD_CORE_OBJS) -lm

run-chronicle-test: test-chronicle
	./test-chronicle

# Navigational aide + hunter's-shack quest activation (storyline JSON).
src/test_nav_aide.o: src/test_nav_aide.c
	$(CC) $(UI_CFLAGS) -c -o src/test_nav_aide.o src/test_nav_aide.c

test-nav-aide: src/test_nav_aide.o src/nav_aide.o src/storyline.o
	$(CC) $(UI_CFLAGS) -o test-nav-aide src/test_nav_aide.o src/nav_aide.o src/storyline.o $(LDFLAGS)

run-nav-aide-test: test-nav-aide
	./test-nav-aide

# Full storyline playthrough: startup gen, chapter/scene, fall, hunter quests, neighbour tour.
# Also a performance probe — phase timings print by default; --csv for machine-readable rows.
src/test_storyline_playthrough.o: src/test_storyline_playthrough.c
	$(CC) $(UI_CFLAGS) -c -o src/test_storyline_playthrough.o src/test_storyline_playthrough.c

test-storyline-playthrough: src/test_storyline_playthrough.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-storyline-playthrough src/test_storyline_playthrough.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-storyline-playthrough-test: test-storyline-playthrough
	./test-storyline-playthrough

run-storyline-playthrough-bench: test-storyline-playthrough
	./test-storyline-playthrough --bench


src/test_voxel_materials.o: src/test_voxel_materials.c
	$(CC) $(CFLAGS) -c -o src/test_voxel_materials.o src/test_voxel_materials.c

test-voxel-materials: src/test_voxel_materials.o
	$(CC) $(CFLAGS) -o test-voxel-materials src/test_voxel_materials.o -lm

run-voxel-materials-test: test-voxel-materials
	./test-voxel-materials

# Movement and collision. Drives the same player_controls and gravity the client does, over terrain
# shaped like the things a generated world puts in the player's way, and asserts after every frame
# that the player is neither inside a solid voxel nor left with nowhere to go.
src/test_movement_audit.o: src/test_movement_audit.c
	$(CC) $(UI_CFLAGS) -c -o src/test_movement_audit.o src/test_movement_audit.c

test-movement-audit: src/test_movement_audit.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-movement-audit src/test_movement_audit.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-movement-audit-test: test-movement-audit
	./test-movement-audit

# The naive save/load round trip: save a game in progress, load it, and check the world, the position
# and the body all came back. Runs in a temporary directory, since both save paths are relative.
src/test_game_save_load.o: src/test_game_save_load.c
	$(CC) $(UI_CFLAGS) -c -o src/test_game_save_load.o src/test_game_save_load.c

test-game-save-load: src/test_game_save_load.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-game-save-load src/test_game_save_load.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-game-save-load-test: test-game-save-load
	./test-game-save-load

src/test_mob_skills.o: src/test_mob_skills.c
	$(CC) $(UI_CFLAGS) -c -o src/test_mob_skills.o src/test_mob_skills.c

test-mob-skills: src/test_mob_skills.o $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)
	$(CC) $(UI_CFLAGS) -o test-mob-skills src/test_mob_skills.o \
	  $(sort $(SPAWN_GRAVITY_OBJS) $(WORLD_CORE_OBJS)) $(LDFLAGS)

run-mob-skills-test: test-mob-skills
	./test-mob-skills

# Sanitizer builds of the threading test. Kept as targets rather than notes so the race and
# memory checks can be re-run after any change to the pool or the jobs. Both need clang, and
# both are slow enough that they stay out of release-check-native; REPS raises the repeat count
# because a scheduling bug shows up intermittently, not on the first run.
# Sorted for the same reason the object groups are: THREAD_SRCS and WORLD_CORE_SRCS both name
# task_scheduler.c, and compiling one translation unit twice into a single binary is a duplicate
# symbol error rather than a no-op.
SANITIZE_SRCS = $(sort src/test_task_scheduler.c $(THREAD_SRCS) $(WORLD_CORE_SRCS) src/wfc.c)
SANITIZE_CFLAGS = -g -O1 -fno-omit-frame-pointer $(NOISE_INCLUDES)
REPS ?= 20

.PHONY: test-task-scheduler-tsan test-task-scheduler-asan sanitize-threads

build/tsan/test-task-scheduler: $(SANITIZE_SRCS)
	@mkdir -p build/tsan
	$(CLANG) -fsanitize=thread $(SANITIZE_CFLAGS) -o $@ $(SANITIZE_SRCS) -lm

build/asan/test-task-scheduler: $(SANITIZE_SRCS)
	@mkdir -p build/asan
	$(CLANG) -fsanitize=address,undefined $(SANITIZE_CFLAGS) -o $@ $(SANITIZE_SRCS) -lm

test-task-scheduler-tsan: build/tsan/test-task-scheduler
	@echo "=== ThreadSanitizer: $(REPS) runs ==="
	@for i in $$(seq 1 $(REPS)); do \
	  ./build/tsan/test-task-scheduler > build/tsan/run.log 2>&1 || { echo "run $$i failed:"; cat build/tsan/run.log; exit 1; }; \
	  grep -q 'ThreadSanitizer' build/tsan/run.log && { echo "run $$i reported a race:"; cat build/tsan/run.log; exit 1; }; \
	done; echo "=== no races in $(REPS) runs ==="

test-task-scheduler-asan: build/asan/test-task-scheduler
	@echo "=== AddressSanitizer + UBSan: $(REPS) runs ==="
	@for i in $$(seq 1 $(REPS)); do \
	  ./build/asan/test-task-scheduler > build/asan/run.log 2>&1 || { echo "run $$i failed:"; cat build/asan/run.log; exit 1; }; \
	done; echo "=== clean in $(REPS) runs ==="

sanitize-threads: test-task-scheduler-tsan test-task-scheduler-asan

run-universe-generate: universe-generate-gameworld
	./universe-generate-gameworld --radius 1

# -------------------------
# Android builds via Gradle
# -------------------------

.PHONY: android-debug android-release

android-debug:
	cd android && ./gradlew assembleDebug | cat
	@echo "APK output: android/app/build/outputs/apk/debug/app-debug.apk"

android-release:
	cd android && ./gradlew assembleRelease | cat
	@echo "APK output: android/app/build/outputs/apk/release/app-release-unsigned.apk"
