typedef enum {
  GOAL_TYPE_NONE,
  GOAL_TYPE_DESIGN
} GoalType;

typedef enum {
  VERSE_HAS_WILDERNESS,
  VERSE_HAS_RIVERS,
  VERSE_HAS_MOUNTAINS,
  VERSE_HAS_LAKES,
  VERSE_HAS_FORESTS,
  VERSE_HAS_OCEANS,
  VERSE_HAS_RIVERS,
  VERSE_HAS_MOUNTAINS,
  VERSE_HAS_LAKES,
  VERSE_HAS_FORESTS,
  VERSE_HAS_ACTORS,
  VERSE_HAS_EPOCHS,
  VERSE_HAS_PHYSICS,
  VERSE_HAS_AI,
  VERSE_HAS_NPCS,
  VERSE_HAS_QUESTS,
  VERSE_HAS_ITEMS,
  VERSE_HAS_INVENTORY,
  VERSE_HAS_ECONOMY,
  VERSE_HAS_SOCIAL_STRUCTURES,
  VERSE_HAS_CULTURE,
  VERSE_HAS_RELIGION,
  VERSE_HAS_MAGIC,
  VERSE_HAS_TECHNOLOGY,
  VERSE_HAS_SCIENCE,
} VerseGoal;

typedef struct {
  GoalType type;
  VerseGoal verse_goal;
} Goal;

void goal_init(Goal *goal, GoalType type, VerseGoal verse_goal);
void goal_update(Goal *goal);
