// Universe Render Reference
//
// This file is used to render the universe and compare the results to a reference
// render. It is used to ensure that the renderer is working correctly and to
// compare the performance of the renderer.
//
// Reference images are generated by running the renderer with the --reset flag.
// This will create a new reference for each of the renderers.

#include <inttypes.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_image.h>
#include <OpenGL/gl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <strings.h>
#include <unistd.h>
#include <sys/stat.h>
#include <time.h>
#include <jansson.h>
#include <ctype.h>
#include "constants.h"
#include "world.h"
#include "isometric_renderer.h"
#include "fp_renderer.h"
#include "voxel_mesh.h"
#include "octree.h"
#include "cpu_renderer_optimized.h"
#include "sprite_renderer.h"

// High-resolution timer for performance measurement
static uint64_t get_time_ns(void)
{
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}

// Helper function to convert string to lowercase
static char* strtolower(char* str) {
  for (char* p = str; *p; ++p) *p = tolower(*p);
  return str;
}

// Render a top-down map using the highest solid voxel per (x,y)
static void render_topdown_highest(SDL_Renderer *ren, const World *w, int screen_w, int screen_h)
{
  if (!ren || !w || screen_w <= 0 || screen_h <= 0)
    return;
  int cell_w = screen_w / (int)w->width;
  int cell_h = screen_h / (int)w->height;
  if (cell_w < 1)
    cell_w = 1;
  if (cell_h < 1)
    cell_h = 1;
  for (uint32_t y = 0; y < w->height; y++)
  {
    for (uint32_t x = 0; x < w->width; x++)
    {
      int top_z = -1;
      for (int z = (int)w->depth - 1; z >= 0; z--)
      {
        const Voxel *vz = world_voxel_cptr_fast((World *)w, (int)x, (int)y, z);
        if (vz && vz->type != VOXEL_AIR)
        {
          top_z = z;
          break;
        }
      }
      uint8_t r = 20, g = 22, b = 35; // background if no solid
      if (top_z >= 0)
      {
        Voxel *v = world_get_voxel((World *)w, x, y, (uint32_t)top_z);
        if (v)
        {
          world_voxel_type_color(v->type, &r, &g, &b);
        }
      }
      SDL_SetRenderDrawColor(ren, r, g, b, 255);
      SDL_Rect rect = {(int)(x * cell_w), (int)(y * cell_h), cell_w, cell_h};
      SDL_RenderFillRect(ren, &rect);
    }
  }
}

// Render with CPU renderer at different optimization levels and export bitmaps
static void render_cpu_optimization_phases(SDL_Renderer *ren, IsometricRenderer *ir, int screen_w, int screen_h)
{
  printf("[CPU-OPT] Rendering optimization phases...\n");

  // Initialize CPU renderer
  cpu_renderer_init_color_table();

  // Define optimization phases to test
  struct {
    const char *name;
    const char *filename;
    CPURenderOptimizations flags;
  } phases[] = {
    {"No Optimizations", "assets/cpu_phase_none.bmp", CPU_RENDER_OPT_NONE},
    {"Chunk Culling", "assets/cpu_phase_chunk.bmp", CPU_RENDER_OPT_CHUNK_CULLING},
    {"Screen Culling", "assets/cpu_phase_screen.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING},
    {"No Face Culling (Quality)", "assets/cpu_phase_quality.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE},
    {"With Face Culling (Performance)", "assets/cpu_phase_performance.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE | CPU_RENDER_OPT_FACE_CULLING},
    {"Batch Rendering", "assets/cpu_phase_batch.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE | CPU_RENDER_OPT_BATCH_RENDERING},
    {"Loop Unrolling", "assets/cpu_phase_loop.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE | CPU_RENDER_OPT_BATCH_RENDERING | CPU_RENDER_OPT_LOOP_UNROLLING},
    {"Memory Alignment", "assets/cpu_phase_memory.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE | CPU_RENDER_OPT_BATCH_RENDERING | CPU_RENDER_OPT_LOOP_UNROLLING | CPU_RENDER_OPT_MEMORY_ALIGNMENT},
    {"SIMD Hints", "assets/cpu_phase_simd.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE | CPU_RENDER_OPT_BATCH_RENDERING | CPU_RENDER_OPT_LOOP_UNROLLING | CPU_RENDER_OPT_MEMORY_ALIGNMENT | CPU_RENDER_OPT_SIMD_HINTS},
    {"Cache Optimization", "assets/cpu_phase_cache.bmp", CPU_RENDER_OPT_CHUNK_CULLING | CPU_RENDER_OPT_SCREEN_CULLING | CPU_RENDER_OPT_COLOR_TABLE | CPU_RENDER_OPT_BATCH_RENDERING | CPU_RENDER_OPT_LOOP_UNROLLING | CPU_RENDER_OPT_MEMORY_ALIGNMENT | CPU_RENDER_OPT_SIMD_HINTS | CPU_RENDER_OPT_CACHE_OPTIMIZATION},
    {"All Optimizations", "assets/cpu_phase_all.bmp", CPU_RENDER_OPT_ALL}
  };

  int num_phases = sizeof(phases) / sizeof(phases[0]);

  for (int phase = 0; phase < num_phases; phase++) {
    printf("[CPU-OPT] Phase %d/%d: %s\n", phase + 1, num_phases, phases[phase].name);

    // Configure CPU renderer
    CPURendererConfig config = {
      .flags = phases[phase].flags,
      .batch_size = 1024,
      .chunk_size_x = 16,
      .chunk_size_y = 16,
      .chunk_size_z = 256,
      .enable_grid = false,
      .enable_debug_overlay = false,
      .max_visible_voxels = 100000,
      .culling_margin = 32.0f
    };

    // Reset stats for this phase
    cpu_renderer_reset_stats();

    // Render with CPU renderer
    Uint64 start_time = SDL_GetPerformanceCounter();
    cpu_renderer_render_optimized(ir, ren, &config);
    Uint64 end_time = SDL_GetPerformanceCounter();

    // Calculate performance
    double freq = (double)SDL_GetPerformanceFrequency();
    double render_time_ms = (double)(end_time - start_time) * 1000.0 / freq;

    // Get statistics
    CPURendererStats stats = cpu_renderer_get_stats();

    // Export bitmap
    SDL_Surface *surf32 = SDL_CreateRGBSurfaceWithFormat(0, screen_w, screen_h, 32, SDL_PIXELFORMAT_ARGB8888);
    if (surf32) {
      if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch) == 0) {
        SDL_Surface *rgb_surf = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
        if (rgb_surf) {
          if (SDL_SaveBMP(rgb_surf, phases[phase].filename) == 0) {
            printf("[CPU-OPT] ✓ Exported %s (%.2f ms, %" PRIu64 " voxels, %" PRIu64 " chunks)\n",
                   phases[phase].filename, render_time_ms, stats.voxels_rendered, stats.chunks_processed);
          } else {
            printf("[CPU-OPT] ✗ Failed to save %s\n", phases[phase].filename);
          }
          SDL_FreeSurface(rgb_surf);
        }
      }
      SDL_FreeSurface(surf32);
    }

    // Print performance summary
    printf("[CPU-OPT] Performance: %.2f ms, %.1f FPS, Culling: %.1f%%\n",
           render_time_ms, 1000.0 / render_time_ms,
           stats.voxels_processed > 0 ? (100.0 * stats.voxels_culled) / stats.voxels_processed : 0.0);
  }

  printf("[CPU-OPT] All optimization phases completed!\n");
}

// Render with sprite renderer at different optimization levels and export bitmaps
static void render_sprite_optimization_phases(SDL_Renderer *ren, IsometricRenderer *ir, int screen_w, int screen_h)
{
  printf("[SPRITE-OPT] Rendering optimization phases...\n");

  // Create sprite renderer
  SpriteRenderer* sprite_renderer = sprite_renderer_create(ren, NULL);
  if (!sprite_renderer) {
    printf("[SPRITE-OPT] Failed to create sprite renderer!\n");
    return;
  }

  // Define optimization phases to test
  struct {
    const char *name;
    const char *filename;
    SpriteRenderOptimizations flags;
  } phases[] = {
    {"No Optimizations", "assets/sprite_phase_none.bmp", SPRITE_RENDER_OPT_NONE},
    {"Screen Culling", "assets/sprite_phase_screen.bmp", SPRITE_RENDER_OPT_SCREEN_CULLING},
    {"Sprite Caching", "assets/sprite_phase_cache.bmp", SPRITE_RENDER_OPT_SCREEN_CULLING | SPRITE_RENDER_OPT_SPRITE_CACHING},
    {"Batch Rendering", "assets/sprite_phase_batch.bmp", SPRITE_RENDER_OPT_SCREEN_CULLING | SPRITE_RENDER_OPT_SPRITE_CACHING | SPRITE_RENDER_OPT_BATCH_RENDERING},
    {"Depth Sorting", "assets/sprite_phase_depth.bmp", SPRITE_RENDER_OPT_SCREEN_CULLING | SPRITE_RENDER_OPT_SPRITE_CACHING | SPRITE_RENDER_OPT_BATCH_RENDERING | SPRITE_RENDER_OPT_DEPTH_SORTING},
    {"All Optimizations", "assets/sprite_phase_all.bmp", SPRITE_RENDER_OPT_ALL}
  };

  int num_phases = sizeof(phases) / sizeof(phases[0]);

  for (int phase = 0; phase < num_phases; phase++) {
    printf("[SPRITE-OPT] Phase %d/%d: %s\n", phase + 1, num_phases, phases[phase].name);

    // Set optimization flags
    sprite_renderer_set_optimizations(&sprite_renderer->config, phases[phase].flags);

    // Reset statistics
    sprite_renderer_reset_stats(sprite_renderer);

    // Render frame
    uint64_t start_time = get_time_ns();
    sprite_renderer_render(sprite_renderer, ir, ren, ir->game_worlds->home_world);
    uint64_t render_time_ns = get_time_ns() - start_time;
    double render_time_ms = render_time_ns / 1000000.0;

    // Get statistics
    SpriteRendererStats stats = sprite_renderer_get_stats(sprite_renderer);

    // Export bitmap using the same approach as CPU renderer
    SDL_Surface *surf32 = SDL_CreateRGBSurfaceWithFormat(0, screen_w, screen_h, 32, SDL_PIXELFORMAT_ARGB8888);
    if (surf32) {
      if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch) == 0) {
        SDL_Surface *rgb_surf = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
        if (rgb_surf) {
          if (SDL_SaveBMP(rgb_surf, phases[phase].filename) == 0) {
            printf("[SPRITE-OPT] ✓ Exported %s (%.2f ms, %" PRIu64 " voxels, %" PRIu64 " sprites)\n",
                   phases[phase].filename, render_time_ms, stats.voxels_rendered, stats.sprites_generated);
          } else {
            printf("[SPRITE-OPT] ✗ Failed to save %s\n", phases[phase].filename);
          }
          SDL_FreeSurface(rgb_surf);
        }
      }
      SDL_FreeSurface(surf32);
    }

    // Print performance
    printf("[SPRITE-OPT] Performance: %.2f ms, %.1f FPS, Culling: %.1f%%\n",
           render_time_ms, 1000.0 / render_time_ms,
           stats.voxels_processed > 0 ? (100.0 * stats.voxels_culled) / stats.voxels_processed : 0.0);
  }

  // Clean up
  sprite_renderer_destroy(sprite_renderer);
  printf("[SPRITE-OPT] All optimization phases completed!\n");
}

// Generate reference outputs for all world types including top-down views
static void generate_world_type_references(SDL_Renderer *ren, IsometricRenderer *ir, int screen_w, int screen_h)
{
  printf("[WORLD-REF] Generating reference outputs for all world types...\n");

  // Define world types to test
  struct {
    const char *name;
    const char *filename;
    WorldGenerationType type;
    const char *seed;
  } world_types[] = {
    {"HOME", "assets/world_type_home.bmp", WORLD_TYPE_HOME, "home_reference_seed"},
    {"FARM", "assets/world_type_farm.bmp", WORLD_TYPE_FARM, "farm_reference_seed"},
    {"RANDOM", "assets/world_type_random.bmp", WORLD_TYPE_RANDOM, "random_reference_seed"},
    {"WILDERNESS", "assets/world_type_wilderness.bmp", WORLD_TYPE_WILDERNESS, "wilderness_reference_seed"},
    {"SOLID", "assets/world_type_solid.bmp", WORLD_TYPE_SOLID, "solid_reference_seed"},
    {"UNDERWORLD", "assets/world_type_underworld.bmp", WORLD_TYPE_UNDERWORLD, "underworld_reference_seed"},
    {"SCOURED", "assets/world_type_scoured.bmp", WORLD_TYPE_SCOURED, "scoured_reference_seed"},
    {"LABYRINTH", "assets/world_type_labyrinth.bmp", WORLD_TYPE_LABYRINTH_SQUARE, "labyrinth_reference_seed"},
    {"WFC_TOWN", "assets/world_type_wfc_town.bmp", WORLD_TYPE_WFC_TOWN, "wfc_town_reference_seed"},
    {"CLOUD", "assets/world_type_cloud.bmp", WORLD_TYPE_CLOUD, "cloud_reference_seed"},
    {"ARENA", "assets/world_type_arena.bmp", WORLD_TYPE_ARENA, "arena_reference_seed"}
  };

  int num_types = sizeof(world_types) / sizeof(world_types[0]);

    for (int type_idx = 0; type_idx < num_types; type_idx++) {
    printf("[WORLD-REF] Processing %s world type...\n", world_types[type_idx].name);

    // Create a test world for this specific type
    World *test_world = world_create(WORLD_SIZE_X, WORLD_SIZE_Y, WORLD_SIZE_Z);
    if (!test_world) {
      printf("[WORLD-REF] Failed to create test world for %s\n", world_types[type_idx].name);
      continue;
    }

    // Generate the world with the specific type
    world_generate_with_type(test_world, world_types[type_idx].seed, world_types[type_idx].type);

    // Temporarily set the world in the renderer so CPU renderer can access it
    World* original_world = ir->game_worlds->home_world;
    ir->game_worlds->home_world = test_world;

        // Debug: Check what's in the generated world
    printf("[WORLD-REF] Generated %s world: %dx%dx%d\n", world_types[type_idx].name,
           (int)test_world->width, (int)test_world->height, (int)test_world->depth);

    // Check a few voxels to see if they're not all AIR
    int check_x = test_world->width / 2;
    int check_y = test_world->height / 2;
    int check_z = test_world->depth / 2;
    Voxel *check_voxel = world_pos_in_bounds_fast(test_world, check_x, check_y, check_z) ?
                         world_voxel_ptr_fast(test_world, check_x, check_y, check_z) : NULL;
    if (check_voxel) {
      printf("[WORLD-REF] Center voxel (%d,%d,%d): type=%d\n", check_x, check_y, check_z, check_voxel->type);
    } else {
      printf("[WORLD-REF] Center voxel (%d,%d,%d): OUT_OF_BOUNDS\n", check_x, check_y, check_z);
    }

    // Check a few more positions to see if there are any non-AIR voxels
    int check_positions[][3] = {{32, 32, 32}, {96, 96, 96}, {64, 64, 32}, {64, 64, 96}};
    for (int i = 0; i < 4; i++) {
      int x = check_positions[i][0], y = check_positions[i][1], z = check_positions[i][2];
      Voxel *v = world_pos_in_bounds_fast(test_world, x, y, z) ?
                  world_voxel_ptr_fast(test_world, x, y, z) : NULL;
      if (v && v->type != VOXEL_AIR) {
        printf("[WORLD-REF] Found non-AIR voxel at (%d,%d,%d): type=%d\n", x, y, z, v->type);
        break;
      }
    }

    // Render isometric view using CPU renderer for consistency
    printf("[WORLD-REF] Rendering %s world with CPU renderer...\n", world_types[type_idx].name);

    // Clear renderer
    SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
    SDL_RenderClear(ren);

    // Render the world using CPU renderer with proper configuration (same as phases)
    CPURendererConfig config = {
      .flags = CPU_RENDER_OPT_ALL,
      .batch_size = 1024,
      .chunk_size_x = 16,
      .chunk_size_y = 16,
      .chunk_size_z = 256,
      .enable_grid = false,
      .enable_debug_overlay = false,
      .max_visible_voxels = 100000,
      .culling_margin = 32.0f
    };

    cpu_renderer_render_optimized(ir, ren, &config);

      // Export isometric view
      SDL_Surface *surf32 = SDL_CreateRGBSurfaceWithFormat(0, screen_w, screen_h, 32, SDL_PIXELFORMAT_ARGB8888);
      if (surf32) {
        if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch) == 0) {
          SDL_Surface *rgb_surf = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
          if (rgb_surf) {
            if (SDL_SaveBMP(rgb_surf, world_types[type_idx].filename) == 0) {
              printf("[WORLD-REF] ✓ Exported %s\n", world_types[type_idx].filename);
            } else {
              printf("[WORLD-REF] ✗ Failed to save %s\n", world_types[type_idx].filename);
            }
            SDL_FreeSurface(rgb_surf);
          }
        }
        SDL_FreeSurface(surf32);
      }

      // Generate top-down view for selected world types
      if (strcmp(world_types[type_idx].name, "HOME") == 0 ||
          strcmp(world_types[type_idx].name, "FARM") == 0 ||
          strcmp(world_types[type_idx].name, "WILDERNESS") == 0 ||
          strcmp(world_types[type_idx].name, "ARENA") == 0) {

                char topdown_filename[256];
        char lower_name[32];
        strcpy(lower_name, world_types[type_idx].name);
        strtolower(lower_name);
        snprintf(topdown_filename, sizeof(topdown_filename), "assets/topdown_%s.bmp", lower_name);

        // Clear renderer for top-down view
        SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
        SDL_RenderClear(ren);

        // Render top-down view
        render_topdown_highest(ren, test_world, screen_w, screen_h);

        // Export top-down view
        SDL_Surface *topdown_surf = SDL_CreateRGBSurfaceWithFormat(0, screen_w, screen_h, 32, SDL_PIXELFORMAT_ARGB8888);
        if (topdown_surf) {
          if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, topdown_surf->pixels, topdown_surf->pitch) == 0) {
            SDL_Surface *topdown_rgb = SDL_ConvertSurfaceFormat(topdown_surf, SDL_PIXELFORMAT_RGB24, 0);
            if (topdown_rgb) {
              if (SDL_SaveBMP(topdown_rgb, topdown_filename) == 0) {
                printf("[WORLD-REF] ✓ Exported %s\n", topdown_filename);
              } else {
                printf("[WORLD-REF] ✗ Failed to save %s\n", topdown_filename);
              }
              SDL_FreeSurface(topdown_rgb);
            }
          }
          SDL_FreeSurface(topdown_surf);
        }
      }

      // Restore the original world and cleanup this test world
      ir->game_worlds->home_world = original_world;
      world_destroy(test_world);
  }



  printf("[WORLD-REF] All world type references generated!\n");
}

// Greedy-mesh top-down renderer: uses voxel_mesh_build_top_faces_greedy to draw
// maximal rectangles per z-slice, scaled to the provided screen size.
static void render_topdown_highest_greedy(SDL_Renderer *ren, const World *w, int screen_w, int screen_h)
{
  if (!ren || !w || screen_w <= 0 || screen_h <= 0)
    return;
  // Compute pixel scale (>=1) per voxel
  int cell_w = screen_w / (int)w->width;
  int cell_h = screen_h / (int)w->height;
  if (cell_w < 1)
    cell_w = 1;
  if (cell_h < 1)
    cell_h = 1;
  VoxelMesh m;
  voxel_mesh_init(&m);
  voxel_mesh_build_top_faces_greedy(w, &m);
  for (int i = 0; i < m.count; i++)
  {
    VoxelFaceQuad q = m.quads[i];
    // Color from representative voxel at (x0,y0,z0)
    Uint8 r = 20, g = 22, b = 35;
    const Voxel *v0 = world_voxel_cptr_fast((World *)w, q.x0, q.y0, q.z0);
    if (v0)
      world_voxel_type_color(v0->type, &r, &g, &b);
    SDL_SetRenderDrawColor(ren, r, g, b, 255);
    // Rectangle spans [x0..x1] and [y0..y1] inclusive in voxel coords
    SDL_Rect rect;
    rect.x = q.x0 * cell_w;
    rect.y = q.y0 * cell_h;
    rect.w = (q.x1 - q.x0 + 1) * cell_w;
    rect.h = (q.y1 - q.y0 + 1) * cell_h;
    SDL_RenderFillRect(ren, &rect);
  }
  voxel_mesh_free(&m);
}

// Validate top-down rendering by drawing at 1:1 pixel-per-voxel and comparing
// readback colors to expected colors from top-most voxel types.
static void validate_topdown_pixel_per_voxel(SDL_Renderer *ren, const World *w)
{
  if (!ren || !w)
    return;
  const int tw = (int)w->width;
  const int th = (int)w->height;
  SDL_Texture *tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_TARGET, tw, th);
  if (!tex)
  {
    fprintf(stderr, "Topdown 1x1: CreateTexture failed: %s\n", SDL_GetError());
    return;
  }
  // Render 1x1
  SDL_SetRenderTarget(ren, tex);
  render_topdown_highest(ren, w, tw, th);
  SDL_SetRenderTarget(ren, NULL);
  // Readback
  SDL_Surface *s = SDL_CreateRGBSurfaceWithFormat(0, tw, th, 32, SDL_PIXELFORMAT_ARGB8888);
  if (!s)
  {
    fprintf(stderr, "Topdown 1x1: CreateRGBSurface failed: %s\n", SDL_GetError());
    SDL_DestroyTexture(tex);
    return;
  }
  if (SDL_SetRenderTarget(ren, tex) == 0)
  {
    if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, s->pixels, s->pitch) != 0)
    {
      fprintf(stderr, "Topdown 1x1: SDL_RenderReadPixels failed: %s\n", SDL_GetError());
    }
    SDL_SetRenderTarget(ren, NULL);
  }
  // Compare each pixel to expected color derived from top voxel type
  int mismatches = 0;
  for (int y = 0; y < th; y++)
  {
    Uint8 *row = (Uint8 *)s->pixels + y * s->pitch;
    for (int x = 0; x < tw; x++)
    {
      // compute expected top voxel color
      int top_z = -1;
      for (int z = (int)w->depth - 1; z >= 0; z--)
      {
        const Voxel *vz = world_voxel_cptr_fast((World *)w, x, y, z);
        if (vz && vz->type != VOXEL_AIR)
        {
          top_z = z;
          break;
        }
      }
      Uint8 er = 20, eg = 22, eb = 35;
      if (top_z >= 0)
      {
        Voxel *v = world_get_voxel((World *)w, (uint32_t)x, (uint32_t)y, (uint32_t)top_z);
        if (v)
        {
          world_voxel_type_color(v->type, &er, &eg, &eb);
        }
      }
      Uint32 px = *(Uint32 *)(row + x * 4);
      Uint8 pr = (Uint8)((px >> 16) & 0xFF);
      Uint8 pg = (Uint8)((px >> 8) & 0xFF);
      Uint8 pb = (Uint8)(px & 0xFF);
      if (pr != er || pg != eg || pb != eb)
        mismatches++;
    }
  }
  if (mismatches == 0)
    printf("[universe-ref] topdown-1x1 validation: ok\n");
  else
    printf("[universe-ref] topdown-1x1 validation: fail (%d mismatched pixels)\n", mismatches);
  SDL_FreeSurface(s);
  SDL_DestroyTexture(tex);
}

// Simple voxel mesh test function - start from ground up
static void test_simple_voxel_mesh(World *w)
{
  printf("\n=== SIMPLE VOXEL MESH TEST (GROUND UP) ===\n");

  // Clear the world first
  memset(w->voxels, 0, w->width * w->height * w->depth * sizeof(Voxel));

  // Test 1: Single voxel at origin
  printf("\n--- Test 1: Single Voxel at (0,0,0) ---\n");
  world_set_voxel(w, 0, 0, 0, VOXEL_STONE);
  printf("Placed single voxel at (0,0,0)\n");

  // Test 2: Two adjacent voxels
  printf("\n--- Test 2: Two Adjacent Voxels at (0,0,0) and (1,0,0) ---\n");
  world_set_voxel(w, 1, 0, 0, VOXEL_STONE);
  printf("Placed second voxel at (1,0,0)\n");

  printf("Expected: Single voxel should have 6 faces, 8 vertices\n");
  printf("Expected: Two adjacent voxels should have 6 faces (shared internal face), 8 vertices (shared edge)\n");
}

// Simple greedy meshing test function
static void test_greedy_meshing_simple(World *w)
{
  printf("\n=== SIMPLE GREEDY MESHING TEST ===\n");

  // Clear the world first
  memset(w->voxels, 0, w->width * w->height * w->depth * sizeof(Voxel));

  // Create a simple 2x2x2 cube in the center
  int center_x = w->width / 2;
  int center_y = w->height / 2;
  int center_z = w->depth / 2;

  printf("Creating 2x2x2 cube at center (%d,%d,%d)\n", center_x, center_y, center_z);

  for (int x = center_x - 1; x <= center_x; x++)
  {
    for (int y = center_y - 1; y <= center_y; y++)
    {
      for (int z = center_z - 1; z <= center_z; z++)
      {
        world_set_voxel(w, x, y, z, VOXEL_STONE);
      }
    }
  }

  printf("Created 8-voxel cube (2x2x2)\n");
}



// Comprehensive greedy meshing test function
static void test_greedy_meshing_comprehensive(World *w)
{
  printf("\n=== COMPREHENSIVE GREEDY MESHING TEST ===\n");

  // Clear the world first
  memset(w->voxels, 0, w->width * w->height * w->depth * sizeof(Voxel));

  // Calculate dynamic coordinates based on world size
  // Position test structures in the center region of the world
  int center_x = w->width / 2;
  int center_y = w->height / 2;
  int center_z = w->depth * 3 / 4; // 75% up from bottom

  // Scale test structure size based on world dimensions
  int test_size = (int)(w->width * 0.03); // 3% of world size
  if (test_size < 8) test_size = 8;       // Minimum size of 8

  printf("World size: %dx%dx%d, Test structures at center (%d,%d,%d), size: %d\n",
         (int)w->width, (int)w->height, (int)w->depth, center_x, center_y, center_z, test_size);

  // Test 1: Complex 3D pattern with holes and overhangs
  printf("\n--- Test 1: Complex 3D Pattern ---\n");

  // Create a test_size x test_size x test_size structure with various features
  int start_x = center_x - test_size/2;
  int start_y = center_y - test_size/2;
  int start_z = center_z - test_size/2;

  for (int x = start_x; x < start_x + test_size; x++)
  {
    for (int y = start_y; y < start_y + test_size; y++)
    {
      for (int z = start_z; z < start_z + test_size; z++)
      {
        // Create a hollow cube with some internal structure
        if ((x == start_x || x == start_x + test_size - 1 ||
             y == start_y || y == start_y + test_size - 1 ||
             z == start_z || z == start_z + test_size - 1) ||
            (x == start_x + test_size/2 && y == start_y + test_size/2 &&
             z >= start_z + test_size/4 && z <= start_z + 3*test_size/4) || // Internal pillar
            (x >= start_x + test_size/4 && x <= start_x + 3*test_size/4 &&
             y >= start_y + test_size/4 && y <= start_y + 3*test_size/4 &&
             z == start_z + test_size/2))
        { // Internal floor
          world_set_voxel(w, x, y, z, VOXEL_STONE);
        }
      }
    }
  }

  // Add some overhanging structures
  for (int x = start_x + test_size/4; x < start_x + 3*test_size/4; x++)
  {
    for (int y = start_y + test_size; y < start_y + test_size + test_size/4; y++)
    {
      world_set_voxel(w, x, y, start_z + 3*test_size/4, VOXEL_STONE);
    }
  }

  // Add floating islands
  for (int x = start_x + test_size + test_size/4; x < start_x + test_size + 3*test_size/4; x++)
  {
    for (int y = start_y + test_size + test_size/4; y < start_y + test_size + 3*test_size/4; y++)
    {
      for (int z = start_z + test_size/4; z < start_z + test_size/2; z++)
      {
        world_set_voxel(w, x, y, z, VOXEL_SOIL);
      }
    }
  }

  // Test 2: Thin walls and corridors
  printf("\n--- Test 2: Thin Walls and Corridors ---\n");

  // Create thin walls
  int wall_start_x = start_x + test_size + test_size/2;
  int wall_start_z = start_z;
  int wall_size = test_size;

  for (int x = wall_start_x; x < wall_start_x + test_size/2; x++)
  {
    for (int z = wall_start_z; z < wall_start_z + test_size; z++)
    {
      if (x == wall_start_x || x == wall_start_x + test_size/2 - 1 ||
          z == wall_start_z || z == wall_start_z + test_size - 1)
      {
        world_set_voxel(w, x, start_y + test_size/4, z, VOXEL_STONE);
      }
    }
  }

  // Create a corridor with pillars
  for (int x = wall_start_x + 1; x < wall_start_x + test_size/2 - 1; x++)
  {
    for (int z = wall_start_z + 1; z < wall_start_z + test_size - 1; z++)
    {
      if (z == wall_start_z + 1 || z == wall_start_z + test_size - 2 ||
          (x == wall_start_x + test_size/4 && (z == wall_start_z + test_size/4 || z == wall_start_z + 3*test_size/4)))
      {
        world_set_voxel(w, x, start_y + test_size/4, z, VOXEL_STONE);
      }
    }
  }

  // Test 3: Staircase pattern
  printf("\n--- Test 3: Staircase Pattern ---\n");

  int stair_start_x = start_x + test_size + test_size;
  int stair_start_y = start_y;
  int stair_start_z = start_z;

  for (int step = 0; step < test_size/2; step++)
  {
    for (int x = stair_start_x; x < stair_start_x + step + 1; x++)
    {
      for (int y = stair_start_y; y < stair_start_y + step + 1; y++)
      {
        world_set_voxel(w, x, y, stair_start_z + step, VOXEL_STONE);
      }
    }
  }

  // Test 4: Checkerboard pattern (tests edge case merging)
  printf("\n--- Test 4: Checkerboard Pattern ---\n");

  int checker_start_x = start_x + test_size + test_size + test_size/2;
  int checker_start_y = start_y;
  int checker_start_z = start_z;

  for (int x = checker_start_x; x < checker_start_x + test_size; x++)
  {
    for (int y = checker_start_y; y < checker_start_y + test_size; y++)
    {
      for (int z = checker_start_z; z < checker_start_z + test_size; z++)
      {
        if (((x + y + z) % 2) == 0)
        {
          world_set_voxel(w, x, y, z, VOXEL_STONE);
        }
      }
    }
  }

  // Test 5: L-shaped structure (tests non-rectangular merging)
  printf("\n--- Test 5: L-Shaped Structure ---\n");

  int l_start_x = start_x + test_size + test_size + test_size;
  int l_start_y = start_y;
  int l_start_z = start_z;

  // Horizontal part of L
  for (int x = l_start_x; x < l_start_x + test_size/2; x++)
  {
    for (int y = l_start_y; y < l_start_y + test_size/4; y++)
    {
      world_set_voxel(w, x, y, l_start_z, VOXEL_STONE);
    }
  }

  // Vertical part of L
  for (int x = l_start_x; x < l_start_x + test_size/4; x++)
  {
    for (int y = l_start_y; y < l_start_y + test_size/2; y++)
    {
      world_set_voxel(w, x, y, l_start_z, VOXEL_STONE);
    }
  }

  // Test 6: Single voxel surrounded by air (edge case)
  printf("\n--- Test 6: Single Voxel Edge Case ---\n");
  world_set_voxel(w, l_start_x + test_size/2, start_y + test_size/4, l_start_z + test_size/4, VOXEL_STONE);

  // Test 7: Large flat surface (tests wide merging)
  printf("\n--- Test 7: Large Flat Surface ---\n");
  int surface_start_x = start_x;
  int surface_start_z = start_z + test_size + test_size/4;

  for (int x = surface_start_x; x < surface_start_x + test_size; x++)
  {
    for (int z = surface_start_x; z < surface_start_x + test_size; z++)
    {
      world_set_voxel(w, x, start_y + test_size/2, z, VOXEL_GRASS);
    }
  }

  // Test 8: Vertical column (tests height merging)
  printf("\n--- Test 8: Vertical Column ---\n");
  int column_x = start_x + test_size/2;
  int column_z = start_z + test_size/2;

  for (int y = start_y; y < start_y + test_size; y++)
  {
    world_set_voxel(w, column_x, y, column_z, VOXEL_STONE);
  }

  printf("\n--- Complex Test World Created ---\n");
  printf("World dimensions: %dx%dx%d\n", (int)w->width, (int)w->height, (int)w->depth);

  // Count total voxels for verification
  int total_voxels = 0;
  for (int x = 0; x < w->width; x++)
  {
    for (int y = 0; y < w->height; y++)
    {
      for (int z = 0; z < w->depth; z++)
      {
        const Voxel *v = world_voxel_cptr_fast(w, x, y, z);
        if (v && v->type != VOXEL_AIR)
        {
          total_voxels++;
        }
      }
    }
  }
  printf("Total non-air voxels: %d\n", total_voxels);
}

// Analyze greedy meshing results for correctness
static void analyze_greedy_meshing_results(const VoxelMesh *mesh, const World *w)
{
  printf("\n=== GREEDY MESHING ANALYSIS ===\n");

  if (!mesh || !w)
  {
    printf("ERROR: Invalid mesh or world for analysis\n");
    return;
  }

  printf("Generated %d quads\n", mesh->count);

  // Analyze each quad for correctness
  for (int i = 0; i < mesh->count; i++)
  {
    const VoxelFaceQuad *q = &mesh->quads[i];
    printf("\nQuad %d: face=%d, pos=(%d,%d,%d) to (%d,%d,%d)\n",
           i, q->face, q->x0, q->y0, q->z0, q->x1, q->y1, q->z1);

    // Calculate expected dimensions
    int width = q->x1 - q->x0 + 1;
    int height = q->y1 - q->y0 + 1;
    int depth = q->z1 - q->z0 + 1;

    printf("  Dimensions: %dx%dx%d\n", width, height, depth);

    // Verify that all voxels in the quad area are solid
    bool all_solid = true;
    int solid_count = 0;
    int total_voxels = 0;

    for (int x = q->x0; x <= q->x1; x++)
    {
      for (int y = q->y0; y <= q->y1; y++)
      {
        for (int z = q->z0; z <= q->z1; z++)
        {
          if (x >= 0 && x < w->width && y >= 0 && y < w->height && z >= 0 && z < w->depth)
          {
            total_voxels++;
            const Voxel *v = world_voxel_cptr_fast(w, x, y, z);
            if (v && v->type != VOXEL_AIR)
            {
              solid_count++;
            }
            else
            {
              all_solid = false;
            }
          }
        }
      }
    }

    printf("  Coverage: %d/%d voxels are solid\n", solid_count, total_voxels);

    // Check if this quad represents a valid face (has air neighbors)
    bool has_air_neighbor = false;
    int air_neighbor_count = 0;

    // Check neighbors in the face direction
    for (int x = q->x0; x <= q->x1; x++)
    {
      for (int y = q->y0; y <= q->y1; y++)
      {
        int nx, ny, nz;
        int z = q->z0; // Use the z coordinate from the quad

        switch (q->face)
        {
        case 0: // +Z face
          nx = x;
          ny = y;
          nz = q->z1 + 1;
          break;
        case 1: // -Z face
          nx = x;
          ny = y;
          nz = q->z0 - 1;
          break;
        case 2: // +Y face
          nx = x;
          ny = q->y1 + 1;
          nz = z;
          break;
        case 4: // -Y face
          nx = x;
          ny = q->y0 - 1;
          nz = z;
          break;
        case 3: // +X face
          nx = q->x1 + 1;
          ny = y;
          nz = z;
          break;
        case 5: // -X face
          nx = q->x0 - 1;
          ny = y;
          nz = z;
          break;
        default:
          nx = ny = nz = -1;
          break;
        }

        if (nx >= 0 && nx < w->width && ny >= 0 && ny < w->height && nz >= 0 && nz < w->depth)
        {
          const Voxel *nb = world_voxel_cptr_fast(w, nx, ny, nz);
          if (!nb || nb->type == VOXEL_AIR)
          {
            has_air_neighbor = true;
            air_neighbor_count++;
          }
        }
        else
        {
          // Edge of world counts as air
          has_air_neighbor = true;
          air_neighbor_count++;
        }
      }
    }

    printf("  Face validity: %s (%d air neighbors)\n",
           has_air_neighbor ? "VALID" : "INVALID", air_neighbor_count);

    // Check for overlapping quads (this would indicate a bug)
    for (int j = i + 1; j < mesh->count; j++)
    {
      const VoxelFaceQuad *q2 = &mesh->quads[j];
      if (q->face == q2->face)
      {
        // Check if quads overlap on the same face
        bool overlaps = !(q->x1 < q2->x0 || q2->x1 < q->x0 ||
                          q->y1 < q2->y0 || q2->y1 < q->y0 ||
                          q->z1 < q2->z0 || q2->z1 < q->z0);

        if (overlaps)
        {
          printf("  WARNING: Overlaps with quad %d!\n", j);
        }
      }
    }
  }

  // Calculate efficiency metrics
  int total_surface_voxels = 0;
  for (int x = 0; x < w->width; x++)
  {
    for (int y = 0; y < w->height; y++)
    {
      for (int z = 0; z < w->depth; z++)
      {
        const Voxel *v = world_voxel_cptr_fast(w, x, y, z);
        if (v && v->type != VOXEL_AIR)
        {
          // Check if this voxel has any air neighbors (is a surface voxel)
          bool is_surface = false;
          for (int dx = -1; dx <= 1; dx++)
          {
            for (int dy = -1; dy <= 1; dy++)
            {
              for (int dz = -1; dz <= 1; dz++)
              {
                if (dx == 0 && dy == 0 && dz == 0)
                  continue;

                int nx = x + dx, ny = y + dy, nz = z + dz;
                if (nx >= 0 && nx < w->width && ny >= 0 && ny < w->height && nz >= 0 && nz < w->depth)
                {
                  const Voxel *nb = world_voxel_cptr_fast(w, nx, ny, nz);
                  if (!nb || nb->type == VOXEL_AIR)
                  {
                    is_surface = true;
                    break;
                  }
                }
                else
                {
                  is_surface = true;
                  break;
                }
              }
              if (is_surface)
                break;
            }
            if (is_surface)
              break;
          }
          if (is_surface)
            total_surface_voxels++;
        }
      }
    }
  }

  printf("\n=== EFFICIENCY ANALYSIS ===\n");
  printf("Total surface voxels: %d\n", total_surface_voxels);
  printf("Generated quads: %d\n", mesh->count);
  printf("Theoretical minimum quads: %d (if perfect merging)\n", (total_surface_voxels + 3) / 4);
  printf("Efficiency: %.1f%%\n", (float)(total_surface_voxels * 100) / (mesh->count * 4));
}



int main(int argc, char **argv)
{
  printf("[MAIN] Starting universe reference program\n");

  // Flag to control test world vs reference world
  bool use_test_world = false;
  bool mesh_only = false;
  bool comprehensive_greedy = false;
  bool simple_greedy = false;
  bool simple_voxel = false;
  bool test_octree = false;
  bool progressive_optimization = false;
  bool cpu_optimization_phases = false;
  bool sprite_optimization_phases = false;
  bool world_type_references = false;

  for (int i = 1; i < argc; i++)
  {
    if (strcmp(argv[i], "--test-world") == 0)
    {
      use_test_world = true;
      printf("[MAIN] Test world mode enabled\n");
    }
    else if (strcmp(argv[i], "--mesh-only") == 0)
    {
      mesh_only = true;
      printf("[MAIN] Mesh-only mode enabled - will exit after mesh generation\n");
    }
    else if (strcmp(argv[i], "--comprehensive-greedy") == 0)
    {
      comprehensive_greedy = true;
      printf("[MAIN] Running comprehensive greedy meshing tests\n");
    }
    else if (strcmp(argv[i], "--simple-greedy") == 0)
    {
      simple_greedy = true;
      printf("[MAIN] Running simple greedy meshing tests\n");
    }
    else if (strcmp(argv[i], "--simple-voxel") == 0)
    {
      simple_voxel = true;
      printf("[MAIN] Running simple voxel mesh test (ground up)\n");
    }
    else if (strcmp(argv[i], "--progressive-optimization") == 0)
    {
      progressive_optimization = true;
      printf("[MAIN] Progressive optimization mode enabled\n");
    }
    else if (strcmp(argv[i], "--cpu-optimization-phases") == 0)
    {
      cpu_optimization_phases = true;
      printf("[MAIN] CPU optimization phases mode enabled\n");
    }
    else if (strcmp(argv[i], "--sprite-optimization-phases") == 0)
    {
      sprite_optimization_phases = true;
      printf("[MAIN] Sprite optimization phases mode enabled\n");
    }
    else if (strcmp(argv[i], "--world-type-references") == 0)
    {
      world_type_references = true;
      printf("[MAIN] World type reference generation mode enabled\n");
    }
    else if (strcmp(argv[i], "--help") == 0)
    {
      printf("Usage: %s [options]\n", argv[0]);
      printf("Options:\n");
      printf("  --test-world          Use test world instead of loading from file\n");
      printf("  --mesh-only           Exit after mesh generation\n");
      printf("  --comprehensive-greedy Run comprehensive greedy meshing tests\n");
      printf("  --simple-greedy       Run simple greedy meshing tests\n");
      printf("  --simple-voxel        Run simple voxel mesh test (ground up)\n");
      printf("  --progressive-optimization Run tests from least to most optimized\n");
      printf("  --cpu-optimization-phases Run CPU renderer optimization phases\n");
      printf("  --sprite-optimization-phases Run sprite renderer optimization phases\n");
      printf("  --world-type-references Generate reference outputs for all world types\n");
      printf("  --help                Show this help message\n");
      printf("\nOutputs:\n");
      printf("  Bitmaps: assets/*.bmp (isometric, first-person views)\n");
      printf("  Meshes: assets/*.obj (voxel meshes for 3D viewers)\n");
      printf("  Reports: reports/*.json (performance timing data)\n");
      printf("  CPU Phases: assets/cpu_phase_*.bmp (optimization phase renders)\n");
      printf("  Sprite Phases: assets/sprite_phase_*.bmp (sprite renderer optimization phases)\n");
      printf("  World Types: assets/world_type_*.bmp (reference renders for each world type)\n");
      printf("  Top-Down Views: assets/topdown_*.bmp (top-down reference renders)\n");
      return 0;
    }
  }

  bool reset_reference = false;
  for (int i = 1; i < argc; i++)
  {
    if (strcmp(argv[i], "--reset") == 0)
      reset_reference = true;
  }
  printf("[MAIN] Reset reference: %s\n", reset_reference ? "true" : "false");
  if (SDL_Init(SDL_INIT_VIDEO) != 0)
  {
    fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
    return 1;
  }

  const int W = 800, H = 600;
  // Prepare an OpenGL context (for GPU depth buffering in mesh path)
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
  SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
  SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
  SDL_Window *win = SDL_CreateWindow("universe-ref", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, W, H, SDL_WINDOW_HIDDEN | SDL_WINDOW_OPENGL);
  if (!win)
  {
    fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
    SDL_Quit();
    return 1;
  }
  // Create and hold a GL context; we won't present, we render to FBOs in FP GL path
  SDL_GLContext glctx = SDL_GL_CreateContext(win);
  if (!glctx) {
    fprintf(stderr, "SDL_GL_CreateContext failed: %s\n", SDL_GetError());
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 1;
  }

  // Initialize FP renderer OpenGL state
  fp_renderer_gl_init();
  SDL_Renderer *ren = SDL_CreateRenderer(win, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
  if (!ren)
  {
    fprintf(stderr, "SDL_CreateRenderer failed: %s\n", SDL_GetError());
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 1;
  }

  // Create a universe with home world
  GameWorlds *gw = game_worlds_create("reference");
  if (!gw || !game_worlds_generate_all(gw, "reference"))
  {
    fprintf(stderr, "Failed to create/generate game worlds\n");
    if (gw)
      game_worlds_destroy(gw);
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 1;
  }

  // Create output directories early to ensure mesh files are saved in the right location
  (void)system("mkdir -p assets");
  (void)system("mkdir -p reports");

  // Create a simple test world for debugging mesh generation (only when flag is set)
  const World *mesh_test_world = NULL;

  // Variable to store octree for progressive optimization tests
  Octree *progressive_test_octree = NULL;

  if (use_test_world)
  {
    printf("[MAIN] Using actual game world for optimization testing\n");
    printf("[MAIN] Home world: %dx%dx%d with %s generation\n",
           (int)gw->home_world->width, (int)gw->home_world->height, (int)gw->home_world->depth,
           "WORLD_TYPE_HOME");

    // Ensure the world is large enough for testing (should be WORLD_SIZE_CUBE = 256)
    if (gw->home_world->width < 256 || gw->home_world->height < 256 || gw->home_world->depth < 256)
    {
      printf("[MAIN] Warning: Game world is smaller than expected 256x256x256\n");
      printf("[MAIN] Actual size: %dx%dx%d\n",
             (int)gw->home_world->width, (int)gw->home_world->height, (int)gw->home_world->depth);
    }

    // Count non-air voxels to understand world complexity
    int voxel_count = 0;
    size_t total_voxels = gw->home_world->width * gw->home_world->height * gw->home_world->depth;
    for (size_t i = 0; i < total_voxels; i++)
    {
      if (gw->home_world->voxels[i].type != VOXEL_AIR)
      {
        voxel_count++;
      }
    }
    printf("[MAIN] Game world contains %d non-air voxels (%.2f%% density)\n",
           voxel_count, (voxel_count * 100.0) / total_voxels);

    // Note: Octree will be created by the FP renderer when needed
    printf("[MAIN] Octree will be created by FP renderer during optimization tests\n");

    // Set mesh_test_world to use the actual game world
    mesh_test_world = gw->home_world;
    printf("[MAIN] Using actual game world for optimization testing\n");
  }
  else
  {
    // Use the reference world by default
    mesh_test_world = gw->home_world;
    printf("[MAIN] Using reference world (128x128x128)\n");
  }

  // Define camera in main function scope so all rendering modes can access it
  FPCamera cam;

  // Position camera to match World Editor's FP renderer positioning
  // Use spawn location (center of world, above terrain) for consistent comparison
  int cx = (int)(gw->home_world->width / 2);
  int cy = (int)(gw->home_world->height / 2);
  int az = (int)(gw->home_world->depth * 0.75f); // 75% up from bottom (above typical terrain)

  cam.fov_deg = 60.0f;
  cam.x = (float)cx + 0.5f;                    // Center X + offset
  cam.y = (float)cy + 0.5f;                    // Center Y + offset
  cam.z = (float)az + 1.5f;                    // Above terrain for better view
  cam.yaw = 0.0f;                              // Face forward (north) - match World Editor
  cam.pitch = 0.0f;                            // Look horizontally - match World Editor
  cam.roll = 0.0f;

  printf("[MAIN] Camera positioned at (%.1f,%.1f,%.1f) to view game world content\n",
         cam.x, cam.y, cam.z);

  // Progressive optimization test sequence (after camera declaration for scope access)
  if (progressive_optimization)
  {
    printf("\n=== PROGRESSIVE OPTIMIZATION TEST SEQUENCE ===\n");

    // Test 1: Naive implementation (no octree, no mesh)
    printf("\n[PROGRESSIVE] Test 1: Naive implementation (no optimizations)\n");
    // Clear any existing octree cache
    fp_renderer_invalidate_cache();
    fp_renderer_enable_gpu_mesh(false);                 // Disable mesh generation

    // Render with naive approach and measure performance
    Uint64 naive_start = SDL_GetPerformanceCounter();
    fp_renderer_render_neighbors(ren, gw, &cam, 0, 0, 800, 600, 0, NULL);
    Uint64 naive_end = SDL_GetPerformanceCounter();
    Uint64 freq = SDL_GetPerformanceFrequency();
    double naive_time = (double)(naive_end - naive_start) / freq * 1000.0;
    printf("[PROGRESSIVE] Test 1 completed: %.2f ms (baseline)\n", naive_time);

    // Test 2: Add octree spatial acceleration
    printf("\n[PROGRESSIVE] Test 2: Adding octree spatial acceleration\n");
    // Build octree using FP renderer's internal mechanism
    fp_renderer_build_world_octree(gw->home_world);
    fp_renderer_enable_gpu_mesh(false);                                    // Keep mesh disabled

    // Render with octree optimization and measure performance
    Uint64 octree_start = SDL_GetPerformanceCounter();
    fp_renderer_render_neighbors(ren, gw, &cam, 0, 0, 800, 600, 0, NULL);
    Uint64 octree_end = SDL_GetPerformanceCounter();
    double octree_time = (double)(octree_end - octree_start) / freq * 1000.0;
    double octree_speedup = naive_time / octree_time;
    printf("[PROGRESSIVE] Test 2 completed: %.2f ms (%.2fx speedup)\n", octree_time, octree_speedup);

    // Test 3: Add mesh generation + octree
    printf("\n[PROGRESSIVE] Test 3: Adding mesh generation + octree\n");
    // Keep octree enabled (it's already built from test 2)
    fp_renderer_enable_gpu_mesh(true);                                     // Enable mesh generation
    fp_renderer_set_mode(FP_MODE_MESH);                                    // Set to mesh mode

    // Render with full optimization and measure performance
    Uint64 mesh_start = SDL_GetPerformanceCounter();
    fp_renderer_render_neighbors(ren, gw, &cam, 0, 0, 800, 600, 0, NULL);
    Uint64 mesh_end = SDL_GetPerformanceCounter();
    double mesh_time = (double)(mesh_end - mesh_start) / freq * 1000.0;
    double mesh_speedup = naive_time / mesh_time;
    printf("[PROGRESSIVE] Test 3 completed: %.2f ms (%.2fx speedup)\n", mesh_time, mesh_speedup);

    // Summary
    printf("\n[PROGRESSIVE] OPTIMIZATION SUMMARY:\n");
    printf("  Baseline (naive):     %.2f ms\n", naive_time);
    printf("  + Octree:             %.2f ms (%.2fx speedup)\n", octree_time, octree_speedup);
    printf("  + Mesh + Octree:      %.2f ms (%.2fx speedup)\n", mesh_time, mesh_speedup);
    printf("  Total improvement:    %.2fx faster than baseline\n", mesh_speedup);

    printf("\n[PROGRESSIVE] All optimization tests completed!\n");

    printf("[PROGRESSIVE] Progressive tests completed (octree managed by FP renderer)\n");
  }

  if (comprehensive_greedy)
  {
    printf("Running comprehensive greedy meshing tests...\n");

    // Create a fresh world for testing
    World test_world;
    test_world.width = 64;
    test_world.height = 64;
    test_world.depth = 64;
    test_world.voxels = (Voxel *)calloc(test_world.width * test_world.height * test_world.depth, sizeof(Voxel));

    if (!test_world.voxels)
    {
      fprintf(stderr, "Failed to allocate test world\n");
      return 1;
    }

    // Run comprehensive tests
    test_greedy_meshing_comprehensive(&test_world);

    // Generate mesh using greedy algorithm
    VoxelMesh mesh = {0};
    voxel_mesh_build_all_faces_greedy(&test_world, &mesh);

    // Analyze results
    analyze_greedy_meshing_results(&mesh, &test_world);

    // Cleanup
    free(mesh.quads);
    free(test_world.voxels);

    printf("\nComprehensive greedy meshing test complete.\n");
    return 0;
  }

  if (simple_greedy)
  {
    printf("Running simple greedy meshing tests...\n");

    // Create a fresh world for testing
    World test_world;
    test_world.width = 64;
    test_world.height = 64;
    test_world.depth = 64;
    test_world.voxels = (Voxel *)calloc(test_world.width * test_world.height * test_world.depth, sizeof(Voxel));

    if (!test_world.voxels)
    {
      fprintf(stderr, "Failed to allocate test world\n");
      return 1;
    }

    // Run simple tests
    test_greedy_meshing_simple(&test_world);

    // Generate mesh using greedy algorithm
    VoxelMesh mesh = {0};
    voxel_mesh_build_all_faces_greedy(&test_world, &mesh);

    // Analyze results
    analyze_greedy_meshing_results(&mesh, &test_world);

    // Cleanup
    free(mesh.quads);
    free(test_world.voxels);

    printf("\nSimple greedy meshing test complete.\n");
    return 0;
  }

  if (simple_voxel)
  {
    printf("Running simple voxel mesh test (ground up)...\n");

    // Create a fresh world for testing - small size for simple test
    World test_world;
    test_world.width = 4;
    test_world.height = 4;
    test_world.depth = 4;
    test_world.voxels = (Voxel *)calloc(test_world.width * test_world.height * test_world.depth, sizeof(Voxel));

    if (!test_world.voxels)
    {
      fprintf(stderr, "Failed to allocate test world\n");
      return 1;
    }

      // Test 1: Single voxel at (0,0,0)
  printf("\n=== TEST 1: SINGLE VOXEL ===\n");
  memset(test_world.voxels, 0, test_world.width * test_world.height * test_world.depth * sizeof(Voxel));
  world_set_voxel(&test_world, 0, 0, 0, VOXEL_STONE);
  printf("Placed single voxel at (0,0,0)\n");

  VoxelMesh single_mesh = {0};
  voxel_mesh_build_all_faces_greedy(&test_world, &single_mesh);

  printf("Single voxel mesh: %d quads\n", single_mesh.count);
  analyze_greedy_meshing_results(&single_mesh, &test_world);

  // Export single voxel mesh
  if (voxel_mesh_export_obj(&single_mesh, "assets/voxel_mesh_single_voxel.obj"))
  {
    printf("Successfully exported single voxel mesh to assets/voxel_mesh_single_voxel.obj\n");
  }
  else
  {
    printf("Failed to export single voxel mesh\n");
  }

  free(single_mesh.quads);

  // Test 2: Two adjacent voxels at (0,0,0) and (1,0,0)
  printf("\n=== TEST 2: TWO ADJACENT VOXELS ===\n");
  world_set_voxel(&test_world, 1, 0, 0, VOXEL_STONE);
  printf("Added second voxel at (1,0,0)\n");

  VoxelMesh two_mesh = {0};
  voxel_mesh_build_all_faces_greedy(&test_world, &two_mesh);

  printf("Two voxel mesh: %d quads\n", two_mesh.count);
  analyze_greedy_meshing_results(&two_mesh, &test_world);

  // Export two voxel mesh
  if (voxel_mesh_export_obj(&two_mesh, "assets/voxel_mesh_two_voxels.obj"))
  {
    printf("Successfully exported two voxel mesh to assets/voxel_mesh_two_voxels.obj\n");
  }
  else
  {
    printf("Failed to export two voxel mesh\n");
  }

  free(two_mesh.quads);

  // Test 3: Three voxels - two adjacent on ground, one stacked on top
  printf("\n=== TEST 3: THREE VOXELS (2 ADJACENT + 1 STACKED) ===\n");
  world_set_voxel(&test_world, 0, 0, 1, VOXEL_STONE);  // Add voxel on top of (0,0,0)
  printf("Added third voxel at (0,0,1) - stacked on top of first voxel\n");

  VoxelMesh three_mesh = {0};
  voxel_mesh_build_all_faces_greedy(&test_world, &three_mesh);

  printf("Three voxel mesh: %d quads\n", three_mesh.count);
  analyze_greedy_meshing_results(&three_mesh, &test_world);

  // Export three voxel mesh
  if (voxel_mesh_export_obj(&three_mesh, "assets/voxel_mesh_three_voxels.obj"))
  {
    printf("Successfully exported three voxel mesh to assets/voxel_mesh_three_voxels.obj\n");
  }
  else
  {
    printf("Failed to export three voxel mesh\n");
  }

  free(three_mesh.quads);
  free(test_world.voxels);

  printf("\nSimple voxel mesh test complete.\n");
  return 0;
  }

  // Set up isometric renderer for the home world only (no neighbors)
  IsometricRenderer *ir = isometric_renderer_create(W, H);
  if (!ir)
  {
    fprintf(stderr, "isometric_renderer_create failed\n");
    game_worlds_destroy(gw);
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 1;
  }
  isometric_renderer_set_game_worlds(ir, gw);
  isometric_renderer_set_screen_size(ir, W, H);
  isometric_renderer_set_auto_center(ir, false);
  ir->neighbor_inclusion_radius = 0;
  if (gw->home_world)
  {
    ir->camera_x = (int)gw->home_world->width / 2;
    ir->camera_y = (int)gw->home_world->height / 2;
    ir->camera_z = (int)gw->home_world->depth - 1; // render full depth up to max Z
  }
  const World *home = gw->home_world;

  // Timing helpers
  Uint64 t0 = SDL_GetPerformanceCounter();

  // Render target
  SDL_Texture *target = SDL_CreateTexture(ren, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_TARGET, W, H);
  if (!target)
  {
    fprintf(stderr, "CreateTexture failed: %s\n", SDL_GetError());
    game_worlds_destroy(gw);
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 1;
  }

  // Loop count from env, default 100
  int runs = 100;
  const char *env_runs = getenv("UNIVERSE_REF_RUNS");
  if (env_runs)
  {
    int r = atoi(env_runs);
    if (r > 0 && r <= 1000)
      runs = r;
  }
  double acc_render_ms = 0.0, acc_read_ms = 0.0, acc_save_ms = 0.0;

  // Reusable readback surface
  SDL_Surface *surf32 = SDL_CreateRGBSurfaceWithFormat(0, W, H, 32, SDL_PIXELFORMAT_ARGB8888);
  if (!surf32)
  {
    fprintf(stderr, "CreateRGBSurface failed: %s\n", SDL_GetError());
    SDL_DestroyTexture(target);
    game_worlds_destroy(gw);
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 1;
  }

  for (int i = 0; i < runs; i++)
  {
    Uint64 tr0 = SDL_GetPerformanceCounter();
    SDL_SetRenderTarget(ren, target);
    isometric_renderer_render_gpu(ir, ren);
    SDL_SetRenderTarget(ren, NULL);
    Uint64 tr1 = SDL_GetPerformanceCounter();

    Uint64 rd0 = tr1;
    if (SDL_SetRenderTarget(ren, target) == 0)
    {
      if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch) != 0)
      {
        fprintf(stderr, "SDL_RenderReadPixels failed: %s\n", SDL_GetError());
      }
      SDL_SetRenderTarget(ren, NULL);
    }
    Uint64 rd1 = SDL_GetPerformanceCounter();

    // Convert and save each run (tmp for non-final runs)
    Uint64 sv0 = rd1;
    SDL_Surface *rgb_tmp = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
    if (!rgb_tmp)
    {
      fprintf(stderr, "SDL_ConvertSurfaceFormat failed: %s\n", SDL_GetError());
    }
    const char *out_path = (i == runs - 1) ? "assets/current.bmp" : "assets/current_tmp.bmp";
    if (rgb_tmp && SDL_SaveBMP(rgb_tmp, out_path) != 0)
    {
      fprintf(stderr, "SDL_SaveBMP (%s) failed: %s\n", out_path, SDL_GetError());
    }
    if (rgb_tmp)
      SDL_FreeSurface(rgb_tmp);
    Uint64 sv1 = SDL_GetPerformanceCounter();

    double freq = (double)SDL_GetPerformanceFrequency();
    acc_render_ms += (double)(tr1 - tr0) * 1000.0 / freq;
    acc_read_ms += (double)(rd1 - rd0) * 1000.0 / freq;
    acc_save_ms += (double)(sv1 - sv0) * 1000.0 / freq;
  }

  double avg_render_ms = acc_render_ms / (double)runs;
  double avg_read_ms = acc_read_ms / (double)runs;
  double avg_save_ms = acc_save_ms / (double)runs;

  // Save both reference and current BMPs as 24-bit RGB for maximal viewer compatibility (current already saved from last run)
  SDL_Surface *rgb_ref = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
  if (!rgb_ref)
  {
    fprintf(stderr, "SDL_ConvertSurfaceFormat failed: %s\n", SDL_GetError());
  }

  // If --reset is provided or reference doesn't exist, write it now; else load and compare to current
  bool need_write_ref = reset_reference;
  if (!need_write_ref)
  {
    FILE *rf = fopen("assets/reference.bmp", "rb");
    if (!rf)
      need_write_ref = true;
    else
      fclose(rf);
  }
  if (need_write_ref)
  {
    if (rgb_ref && SDL_SaveBMP(rgb_ref, "assets/reference.bmp") != 0)
    {
      fprintf(stderr, "SDL_SaveBMP reference failed: %s\n", SDL_GetError());
    }
  }
  Uint64 t_save = SDL_GetPerformanceCounter();

  // Compare assets/current.bmp vs assets/reference.bmp and print diagnostics
  SDL_Surface *ref_loaded = SDL_LoadBMP("assets/reference.bmp");
  SDL_Surface *cur_loaded = SDL_LoadBMP("assets/current.bmp");
  int diff_pixels = -1;
  if (ref_loaded && cur_loaded)
  {
    SDL_Surface *ref32 = SDL_ConvertSurfaceFormat(ref_loaded, SDL_PIXELFORMAT_ARGB8888, 0);
    SDL_Surface *cur32 = SDL_ConvertSurfaceFormat(cur_loaded, SDL_PIXELFORMAT_ARGB8888, 0);
    if (ref32 && cur32 && ref32->w == cur32->w && ref32->h == cur32->h)
    {
      diff_pixels = 0;
      Uint8 *rp = (Uint8 *)ref32->pixels;
      Uint8 *cp = (Uint8 *)cur32->pixels;
      for (int y = 0; y < ref32->h; y++)
      {
        Uint8 *rr = rp + y * ref32->pitch;
        Uint8 *cr = cp + y * cur32->pitch;
        for (int x = 0; x < ref32->w; x++)
        {
          Uint32 *rpx = (Uint32 *)(rr + x * 4);
          Uint32 *cpx = (Uint32 *)(cr + x * 4);
          if (*rpx != *cpx)
            diff_pixels++;
        }
      }
    }
    if (ref32)
      SDL_FreeSurface(ref32);
    if (cur32)
      SDL_FreeSurface(cur32);
  }

  // Persist reference render stats and compare against them on future runs
  const char *report_path = "reports/reference-render.json";
  // Timing report (averaged)
  Uint64 t1 = SDL_GetPerformanceCounter();
  double freq = (double)SDL_GetPerformanceFrequency();
  double dt_render_ms = avg_render_ms;
  double dt_read_ms = avg_read_ms;
  double dt_save_ms = avg_save_ms;
  double dt_total_ms = dt_render_ms + dt_read_ms + dt_save_ms;
  double fps = (dt_total_ms > 0.0) ? (1000.0 / dt_total_ms) : 0.0;

  // If --reset or reference report is missing, write it now
  FILE *jrf = fopen(report_path, "rb");
  if (reset_reference || !jrf)
  {
    if (jrf)
    {
      fclose(jrf);
      jrf = NULL;
    }
    FILE *jw = fopen(report_path, "wb");
    if (jw)
    {
      fprintf(jw,
              "{\n  \"width\": %d,\n  \"height\": %d,\n  \"neighborRadius\": %d,\n  \"runs\": %d,\n  \"render_ms\": %.3f,\n  \"read_ms\": %.3f,\n  \"save_ms\": %.3f,\n  \"total_ms\": %.3f,\n  \"fps\": %.2f\n}\n",
              W, H, 0, runs, dt_render_ms, dt_read_ms, dt_save_ms, dt_total_ms, fps);
      fclose(jw);
      printf("[universe-ref] wrote %s\n", report_path);
    }
  }
  else
  {
    fclose(jrf);
    // Load and compare
    FILE *jr = fopen(report_path, "rb");
    if (jr)
    {
      fseek(jr, 0, SEEK_END);
      long sz = ftell(jr);
      fseek(jr, 0, SEEK_SET);
      char *buf = (char *)malloc(sz + 1);
      if (buf && fread(buf, 1, sz, jr) == (size_t)sz)
      {
        buf[sz] = '\0';
        double ref_total = 0.0;
        double ref_render = 0.0;
        double ref_fps = 0.0;
        char *pt = strstr(buf, "\"total_ms\"");
        if (pt)
          sscanf(pt, "\"total_ms\"%*[^0-9]%lf", &ref_total);
        char *pr = strstr(buf, "\"render_ms\"");
        if (pr)
          sscanf(pr, "\"render_ms\"%*[^0-9]%lf", &ref_render);
        char *pf = strstr(buf, "\"fps\"");
        if (pf)
          sscanf(pf, "\"fps\"%*[^0-9]%lf", &ref_fps);
        if (ref_total > 0.0)
        {
          double delta = dt_total_ms - ref_total;
          double pct = (delta / ref_total) * 100.0;
          printf("[universe-ref] perf: total %.2f ms vs ref %.2f ms (%+.1f%%)\n", dt_total_ms, ref_total, pct);
        }
        if (ref_render > 0.0)
        {
          double delta = dt_render_ms - ref_render;
          double pct = (delta / ref_render) * 100.0;
          printf("[universe-ref] perf: render %.2f ms vs ref %.2f ms (%+.1f%%)\n", dt_render_ms, ref_render, pct);
        }
        if (ref_fps > 0.0)
        {
          double delta = fps - ref_fps;
          double pct = (delta / ref_fps) * 100.0;
          printf("[universe-ref] perf: fps %.2f vs ref %.2f (%+.1f%%)\n", fps, ref_fps, pct);
        }
      }
      if (buf)
        free(buf);
      fclose(jr);
    }
  }
  // Final result reporting
  printf("[universe-ref] timing: render=%.2fms read=%.2fms save=%.2fms total=%.2fms (fps=%.2f)\n", dt_render_ms, dt_read_ms, dt_save_ms, dt_total_ms, fps);
  if (diff_pixels >= 0)
  {
    if (diff_pixels == 0)
      printf("[universe-ref] compare: ok (current.bmp matches reference.bmp)\n");
    else
      printf("[universe-ref] compare: fail (%d pixels differ)\n", diff_pixels);
  }

  // ---------------------------------------------------------------------------
  // Additional outputs: top-down and first-person views
  // Top-down highest-solid at pixel-per-voxel resolution (1:1)
  {
    const int TW = (int)home->width;
    const int TH = (int)home->height;
    SDL_Texture *top_tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_TARGET, TW, TH);
    if (top_tex)
    {
      SDL_SetRenderTarget(ren, top_tex);
      SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
      SDL_RenderClear(ren);
      // Use greedy topdown renderer for efficiency and parity with mesh path
      render_topdown_highest_greedy(ren, home, TW, TH);
      SDL_SetRenderTarget(ren, NULL);
    }
    // Readback 1:1 into dedicated surface
    SDL_Surface *top32 = SDL_CreateRGBSurfaceWithFormat(0, TW, TH, 32, SDL_PIXELFORMAT_ARGB8888);
    if (top32 && top_tex)
    {
      if (SDL_SetRenderTarget(ren, top_tex) == 0)
      {
        if (SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, top32->pixels, top32->pitch) != 0)
        {
          fprintf(stderr, "SDL_RenderReadPixels (topdown) failed: %s\n", SDL_GetError());
        }
        SDL_SetRenderTarget(ren, NULL);
      }
    }
    // Save current 1:1
    SDL_Surface *rgb_top = top32 ? SDL_ConvertSurfaceFormat(top32, SDL_PIXELFORMAT_RGB24, 0) : NULL;
    if (rgb_top)
      SDL_SaveBMP(rgb_top, "assets/current_topdown.bmp");
    // Ensure reference exists or reset
    bool need_write_ref_top = reset_reference;
    if (!need_write_ref_top)
    {
      FILE *f = fopen("assets/reference_topdown.bmp", "rb");
      if (!f)
        need_write_ref_top = true;
      else
        fclose(f);
    }
    if (need_write_ref_top && rgb_top)
      SDL_SaveBMP(rgb_top, "assets/reference_topdown.bmp");
    // Compare (only if sizes match)
    int diff_top = -1;
    SDL_Surface *ref_top = SDL_LoadBMP("assets/reference_topdown.bmp");
    SDL_Surface *cur_top = SDL_LoadBMP("assets/current_topdown.bmp");
    if (ref_top && cur_top)
    {
      SDL_Surface *r32 = SDL_ConvertSurfaceFormat(ref_top, SDL_PIXELFORMAT_ARGB8888, 0);
      SDL_Surface *c32 = SDL_ConvertSurfaceFormat(cur_top, SDL_PIXELFORMAT_ARGB8888, 0);
      if (r32 && c32 && r32->w == c32->w && r32->h == c32->h)
      {
        diff_top = 0;
        Uint8 *rp = (Uint8 *)r32->pixels;
        Uint8 *cp = (Uint8 *)c32->pixels;
        for (int y = 0; y < r32->h; y++)
        {
          Uint8 *rr = rp + y * r32->pitch;
          Uint8 *cr = cp + y * c32->pitch;
          for (int x = 0; x < r32->w; x++)
          {
            if (*(Uint32 *)(rr + x * 4) != *(Uint32 *)(cr + x * 4))
              diff_top++;
          }
        }
      }
      if (r32)
        SDL_FreeSurface(r32);
      if (c32)
        SDL_FreeSurface(c32);
    }
    if (rgb_top)
      SDL_FreeSurface(rgb_top);
    if (top32)
      SDL_FreeSurface(top32);
    if (top_tex)
      SDL_DestroyTexture(top_tex);
    if (ref_top)
      SDL_FreeSurface(ref_top);
    if (cur_top)
      SDL_FreeSurface(cur_top);
    if (diff_top >= 0)
    {
      if (diff_top == 0)
        printf("[universe-ref] compare topdown: ok (current_topdown.bmp matches reference_topdown.bmp)\n");
      else
        printf("[universe-ref] compare topdown: fail (%d pixels differ)\n", diff_top);
    }
    // Additionally validate using 1:1 pixel-per-voxel
    validate_topdown_pixel_per_voxel(ren, home);

    // Benchmark topdown naive vs greedy at 1:1 without affecting outputs
    {
      SDL_Texture *bench_tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_TARGET, TW, TH);
      double greedy_ms = 0.0, naive_ms = 0.0;
      double freq_b = (double)SDL_GetPerformanceFrequency();
      if (bench_tex)
      {
        // Greedy timing
        SDL_SetRenderTarget(ren, bench_tex);
        SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
        SDL_RenderClear(ren);
        Uint64 g0 = SDL_GetPerformanceCounter();
        render_topdown_highest_greedy(ren, home, TW, TH);
        Uint64 g1 = SDL_GetPerformanceCounter();
        greedy_ms = (double)(g1 - g0) * 1000.0 / freq_b;
        // Naive timing
        SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
        SDL_RenderClear(ren);
        Uint64 n0 = SDL_GetPerformanceCounter();
        render_topdown_highest(ren, home, TW, TH);
        Uint64 n1 = SDL_GetPerformanceCounter();
        naive_ms = (double)(n1 - n0) * 1000.0 / freq_b;
        SDL_SetRenderTarget(ren, NULL);
        SDL_DestroyTexture(bench_tex);
      }
      if (greedy_ms > 0.0 && naive_ms > 0.0)
      {
        double delta = greedy_ms - naive_ms;
        double pct = (delta / naive_ms) * 100.0;
        double speedup = (naive_ms / greedy_ms);
        printf("[universe-ref] topdown-1x1 perf: greedy=%.3f ms, naive=%.3f ms (%+.1f%%, %.2fx)\n", greedy_ms, naive_ms, pct, speedup);
      }
    }
  }

  // First-person view
  {
    // Pre-build an FP mesh (all faces) for validation without changing render output
    // Note: build is optional/no-op for perf if not needed; here we just ensure it compiles/runs.
    // The render path remains raycast-based so visuals are unchanged.
    {
      VoxelMesh m;
      voxel_mesh_init(&m);

      // Set environment variable to tell fp_renderer not to export mesh
      setenv("UNIVERSE_REF_SKIP_MESH_EXPORT", "1", 1);

      if (use_test_world)
      {
        printf("[TEST] Building mesh for test world with 8 voxels\n");
        voxel_mesh_build_all_faces_greedy(gw->home_world, &m);
        printf("[TEST] Mesh generation complete: %d quads generated\n", m.count);

        // Export the test world mesh to OBJ for inspection
        if (m.count > 0)
        {
          char cwd[1024];
          if (getcwd(cwd, sizeof(cwd)) != NULL) {
            printf("[TEST] Current working directory: %s\n", cwd);
          }
          printf("[TEST] Exporting test world mesh to assets/voxel_mesh_test.obj\n");
          printf("[TEST] Full path would be: %s/assets/voxel_mesh_test.obj\n", cwd);
          voxel_mesh_export_obj(&m, "assets/voxel_mesh_test.obj");
        }
      }
      else
      {
        printf("[MAIN] Building mesh for reference world (128x128x128)\n");
        voxel_mesh_build_all_faces_greedy(gw->home_world, &m);
        printf("[MAIN] Mesh generation complete: %d quads generated\n", m.count);

        // Export the reference world mesh to OBJ for inspection
        if (m.count > 0)
        {
          char cwd[1024];
          if (getcwd(cwd, sizeof(cwd)) != NULL) {
            printf("[MAIN] Current working directory: %s\n", cwd);
          }
          printf("[MAIN] Exporting reference world mesh to assets/voxel_mesh_debug.obj\n");
          printf("[MAIN] Full path would be: %s/assets/voxel_mesh_debug.obj\n", cwd);
          voxel_mesh_export_obj(&m, "assets/voxel_mesh_debug.obj");
        }
      }

      // Force the renderer to use our fresh mesh instead of cached data
      if (use_test_world)
      {
        printf("[TEST] Forcing renderer to use fresh test world mesh\n");
        fp_renderer_set_cached_mesh(gw->home_world, &m);
      }
      else
      {
        printf("[MAIN] Forcing renderer to use fresh reference world mesh\n");
        fp_renderer_set_cached_mesh(gw->home_world, &m);
      }

      // If mesh-only mode, exit here instead of entering rendering loop
      if (mesh_only)
      {
        printf("[MAIN] Mesh generation complete. Exiting due to --mesh-only flag.\n");
        voxel_mesh_free(&m);
        if (use_test_world)
        {
          // No cleanup needed since we're modifying the home world directly
        }
        game_worlds_destroy(gw);
        SDL_DestroyRenderer(ren);
        SDL_DestroyWindow(win);
        SDL_Quit();
        return 0;
      }
    }
    // Render: default to raycast for stable references; switch to mesh when env asks
    SDL_SetRenderTarget(ren, target);
    SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
    SDL_RenderClear(ren);
    const char *fp_mode = getenv("UNIVERSE_REF_FP_MODE");
    bool use_mesh = (fp_mode && strcmp(fp_mode, "mesh") == 0);
    if (use_mesh)
    {
      // Enable GPU triangles path only when explicitly requested via env
      const char *gpu_env = getenv("UNIVERSE_REF_FP_GPU");
      bool enable_gpu_tris = (gpu_env && (*gpu_env != '\0'));
      fp_renderer_enable_gpu_mesh(enable_gpu_tris);
      if (enable_gpu_tris)
      {
        SDL_GL_MakeCurrent(win, glctx);
        fp_renderer_set_mode(FP_MODE_MESH);  // Set to mesh mode for GPU rendering
      }
      fp_renderer_render(ren, mesh_test_world, &cam, 0, 0, W, H, NULL);
    }
    else
    {
      // Use neighbors path with radius=0 to invoke the original raycast renderer
      // Use gw for current_fp.bmp as it was working correctly
      fp_renderer_render_neighbors(ren, gw, &cam, 0, 0, W, H, 0, NULL);
    }
    SDL_SetRenderTarget(ren, NULL);
    // Readback
    if (SDL_SetRenderTarget(ren, target) == 0)
    {
      SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch);
      SDL_SetRenderTarget(ren, NULL);
    }
    // Save current
    SDL_Surface *rgb_fp = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
    if (rgb_fp)
      SDL_SaveBMP(rgb_fp, "assets/current_fp.bmp");
    // Ensure reference exists or reset
    bool need_write_ref_fp = reset_reference;
    if (!need_write_ref_fp)
    {
      FILE *f = fopen("assets/reference_fp.bmp", "rb");
      if (!f)
        need_write_ref_fp = true;
      else
        fclose(f);
    }
    if (need_write_ref_fp && rgb_fp)
      SDL_SaveBMP(rgb_fp, "assets/reference_fp.bmp");
    // Compare
    int diff_fp = -1;
    SDL_Surface *ref_fp = SDL_LoadBMP("assets/reference_fp.bmp");
    SDL_Surface *cur_fp = SDL_LoadBMP("assets/current_fp.bmp");
    if (ref_fp && cur_fp)
    {
      SDL_Surface *r32 = SDL_ConvertSurfaceFormat(ref_fp, SDL_PIXELFORMAT_ARGB8888, 0);
      SDL_Surface *c32 = SDL_ConvertSurfaceFormat(cur_fp, SDL_PIXELFORMAT_ARGB8888, 0);
      if (r32 && c32 && r32->w == c32->w && r32->h == c32->h)
      {
        diff_fp = 0;
        Uint8 *rp = (Uint8 *)r32->pixels;
        Uint8 *cp = (Uint8 *)c32->pixels;
        for (int y = 0; y < r32->h; y++)
        {
          Uint8 *rr = rp + y * r32->pitch;
          Uint8 *cr = cp + y * c32->pitch;
          for (int x = 0; x < r32->w; x++)
          {
            if (*(Uint32 *)(rr + x * 4) != *(Uint32 *)(cr + x * 4))
              diff_fp++;
          }
        }
      }
      if (r32)
        SDL_FreeSurface(r32);
      if (c32)
        SDL_FreeSurface(c32);
    }
    if (rgb_fp)
      SDL_FreeSurface(rgb_fp);
    if (ref_fp)
      SDL_FreeSurface(ref_fp);
    if (cur_fp)
      SDL_FreeSurface(cur_fp);
    if (diff_fp >= 0)
    {
      if (diff_fp == 0)
        printf("[universe-ref] compare fp: ok (current_fp.bmp matches reference_fp.bmp)\n");
      else
        printf("[universe-ref] compare fp: fail (%d pixels differ)\n", diff_fp);
    }

    // Export first-person view mesh if mesh mode is enabled
    if (use_mesh && mesh_test_world)
    {
      VoxelMesh fp_mesh = {0};
      voxel_mesh_build_all_faces_greedy(mesh_test_world, &fp_mesh);
      if (fp_mesh.count > 0)
      {
        printf("[universe-ref] Exporting first-person view mesh to assets/voxel_mesh_fp.obj (%d quads)\n", fp_mesh.count);
        voxel_mesh_export_obj(&fp_mesh, "assets/voxel_mesh_fp.obj");
      }
      voxel_mesh_free(&fp_mesh);
    }
  }

  // ---------------------------------------------------------------------------
  // Fourth output: "ideal" FP render (flat, raymarch-based) for parity baseline
  {
    // Use the same camera that was adjusted for test world instead of creating a new one
    // FPCamera cam;
    // cam.x = (float)home->width * 0.5f;
    // cam.y = (float)home->height * 0.5f;
    // cam.z = (float)home->depth * 0.75f + 1.0f;
    // cam.yaw = 0.0f;
    // cam.pitch = -0.25f;
    // cam.fov_deg = 60.0f;

    // Force flat shading and ample steps for a clean baseline
    setenv("UNIVERSE_REF_FP_FLAT", "1", 1);
    setenv("UNIVERSE_REF_FP_MAX_STEPS", "100000", 1);
    fp_renderer_set_mode(FP_MODE_RAY);

    SDL_SetRenderTarget(ren, target);
    SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
    SDL_RenderClear(ren);
    fp_renderer_render_neighbors(ren, gw, &cam, 0, 0, W, H, 0, NULL);
    SDL_SetRenderTarget(ren, NULL);

    // Readback
    if (SDL_SetRenderTarget(ren, target) == 0)
    {
      SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch);
      SDL_SetRenderTarget(ren, NULL);
    }
    // Save current ideal
    SDL_Surface *rgb_fp_ideal = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
    if (rgb_fp_ideal)
      SDL_SaveBMP(rgb_fp_ideal, "assets/current_fp_ideal.bmp");
    // Ensure reference exists or reset
    bool need_write_ref_fp_ideal = reset_reference;
    if (!need_write_ref_fp_ideal)
    {
      FILE *f = fopen("assets/reference_fp_ideal.bmp", "rb");
      if (!f)
        need_write_ref_fp_ideal = true;
      else
        fclose(f);
    }
    if (need_write_ref_fp_ideal && rgb_fp_ideal)
      SDL_SaveBMP(rgb_fp_ideal, "assets/reference_fp_ideal.bmp");
    // Compare
    int diff_fp_ideal = -1;
    SDL_Surface *ref_fp_ideal = SDL_LoadBMP("assets/reference_fp_ideal.bmp");
    SDL_Surface *cur_fp_ideal = SDL_LoadBMP("assets/current_fp_ideal.bmp");
    if (ref_fp_ideal && cur_fp_ideal)
    {
      SDL_Surface *r32 = SDL_ConvertSurfaceFormat(ref_fp_ideal, SDL_PIXELFORMAT_ARGB8888, 0);
      SDL_Surface *c32 = SDL_ConvertSurfaceFormat(cur_fp_ideal, SDL_PIXELFORMAT_ARGB8888, 0);
      if (r32 && c32 && r32->w == c32->w && r32->h == c32->h)
      {
        diff_fp_ideal = 0;
        Uint8 *rp = (Uint8 *)r32->pixels;
        Uint8 *cp = (Uint8 *)c32->pixels;
        for (int y = 0; y < r32->h; y++)
        {
          Uint8 *rr = rp + y * r32->pitch;
          Uint8 *cr = cp + y * c32->pitch;
          for (int x = 0; x < r32->w; x++)
          {
            if (*(Uint32 *)(rr + x * 4) != *(Uint32 *)(cr + x * 4))
              diff_fp_ideal++;
          }
        }
      }
      if (r32)
        SDL_FreeSurface(r32);
      if (c32)
        SDL_FreeSurface(c32);
    }
    if (rgb_fp_ideal)
      SDL_FreeSurface(rgb_fp_ideal);
    if (ref_fp_ideal)
      SDL_FreeSurface(ref_fp_ideal);
    if (cur_fp_ideal)
      SDL_FreeSurface(cur_fp_ideal);
    if (diff_fp_ideal >= 0)
    {
      if (diff_fp_ideal == 0)
        printf("[universe-ref] compare fp-ideal: ok (current_fp_ideal.bmp matches reference_fp_ideal.bmp)\n");
      else
        printf("[universe-ref] compare fp-ideal: fail (%d pixels differ)\n", diff_fp_ideal);
    }

    // Optimized variant of ideal: mesh+GPU flat composition, compared against fp-ideal reference
    {
      Uint64 total_start = SDL_GetPerformanceCounter();
      Uint64 freq = SDL_GetPerformanceFrequency();

      setenv("UNIVERSE_REF_FP_FLAT", "1", 1);
      setenv("UNIVERSE_REF_FP_SKY_UNIFORM", "1", 1);
      setenv("UNIVERSE_REF_FP_IDEAL_OPT", "1", 1);
      fp_renderer_set_mode(FP_MODE_RAY);
      fp_renderer_enable_gpu_mesh(false);

      // Ensure OpenGL context is current for the ideal_opt path
      SDL_GL_MakeCurrent(win, glctx);

      // Run 1000 frames to test mesh cache performance
      const int num_frames = 100;
      double first_frame_ms = 0.0;
      double total_render_ms = 0.0;

      printf("[universe-ref] fp-ideal-opt: Running %d frames to test mesh cache performance\n", num_frames);

      for (int frame = 0; frame < num_frames; frame++)
      {
        Uint64 frame_start = SDL_GetPerformanceCounter();

        SDL_SetRenderTarget(ren, target);
        SDL_SetRenderDrawColor(ren, 20, 22, 35, 255);
        SDL_RenderClear(ren);
        fp_renderer_render_neighbors(ren, gw, &cam, 0, 0, W, H, 0, NULL);
        SDL_SetRenderTarget(ren, NULL);

        Uint64 frame_end = SDL_GetPerformanceCounter();
        double frame_ms = (double)(frame_end - frame_start) * 1000.0 / (double)freq;

        if (frame == 0)
        {
          first_frame_ms = frame_ms;
          printf("[universe-ref] fp-ideal-opt: Frame 0 (cache miss): %.2fms\n", first_frame_ms);
        }
        else if (frame == 1)
        {
          printf("[universe-ref] fp-ideal-opt: Frame 1 (cache hit): %.2fms\n", frame_ms);
        }
        else if (frame == 99)
        {
          printf("[universe-ref] fp-ideal-opt: Frame 99 (cache hit): %.2fms\n", frame_ms);
        }
        else if (frame == 999)
        {
          printf("[universe-ref] fp-ideal-opt: Frame 999 (cache hit): %.2fms\n", frame_ms);
        }

        total_render_ms += frame_ms;
      }

      Uint64 total_end = SDL_GetPerformanceCounter();
      double total_ms = (double)(total_end - total_start) * 1000.0 / (double)freq;
      double avg_frame_ms = total_render_ms / (double)num_frames;

      printf("[universe-ref] fp-ideal-opt: Performance over %d frames:\n", num_frames);
      printf("[universe-ref] fp-ideal-opt:   First frame (cache miss): %.2fms\n", first_frame_ms);
      printf("[universe-ref] fp-ideal-opt:   Average frame: %.2fms\n", avg_frame_ms);
      printf("[universe-ref] fp-ideal-opt:   Total time: %.2fms\n", total_ms);
      printf("[universe-ref] fp-ideal-opt:   Cache speedup: %.1fx\n", first_frame_ms / avg_frame_ms);

      // Save the last frame for comparison
      // Since we're using CPU rendering, read from SDL renderer
      if (SDL_SetRenderTarget(ren, target) == 0)
      {
        SDL_RenderReadPixels(ren, NULL, SDL_PIXELFORMAT_ARGB8888, surf32->pixels, surf32->pitch);
        SDL_SetRenderTarget(ren, NULL);
      }
      SDL_Surface *rgb_opt = SDL_ConvertSurfaceFormat(surf32, SDL_PIXELFORMAT_RGB24, 0);
      if (rgb_opt)
        SDL_SaveBMP(rgb_opt, "assets/current_fp_ideal_opt.bmp");

      int diff_fp_opt = -1;
      SDL_Surface *ref_opt = SDL_LoadBMP("assets/reference_fp_ideal.bmp");
      SDL_Surface *cur_opt = SDL_LoadBMP("assets/current_fp_ideal_opt.bmp");
      if (ref_opt && cur_opt)
      {
        SDL_Surface *r32 = SDL_ConvertSurfaceFormat(ref_opt, SDL_PIXELFORMAT_ARGB8888, 0);
        SDL_Surface *c32 = SDL_ConvertSurfaceFormat(cur_opt, SDL_PIXELFORMAT_ARGB8888, 0);
        if (r32 && c32 && r32->w == c32->w && r32->h == c32->h)
        {
          diff_fp_opt = 0;
          Uint8 *rp = (Uint8 *)r32->pixels;
          Uint8 *cp = (Uint8 *)c32->pixels;
          for (int y = 0; y < r32->h; y++)
          {
            Uint8 *rr = rp + y * r32->pitch;
            Uint8 *cr = cp + y * c32->pitch;
            for (int x = 0; x < r32->w; x++)
            {
              if (*(Uint32 *)(rr + x * 4) != *(Uint32 *)(cr + x * 4))
                diff_fp_opt++;
            }
          }
        }
        if (r32)
          SDL_FreeSurface(r32);
        if (c32)
          SDL_FreeSurface(c32);
      }
      if (rgb_opt)
        SDL_FreeSurface(rgb_opt);
      if (ref_opt)
        SDL_FreeSurface(ref_opt);
      if (cur_opt)
        SDL_FreeSurface(cur_opt);

      if (diff_fp_opt >= 0)
      {
        if (diff_fp_opt == 0)
          printf("[universe-ref] compare fp-ideal-opt: ok (current_fp_ideal_opt.bmp matches reference_fp_ideal.bmp)\n");
        else
          printf("[universe-ref] compare fp-ideal-opt: fail (%d pixels differ)\n", diff_fp_opt);
      }

      // Automated sanity: background sky coverage tolerance
      if (rgb_opt)
      {
        int sky_pixels = 0, total = rgb_opt->w * rgb_opt->h;
        Uint8 *p = (Uint8 *)rgb_opt->pixels;
        for (int y = 0; y < rgb_opt->h; y++)
        {
          Uint8 *row = p + y * rgb_opt->pitch;
          for (int x = 0; x < rgb_opt->w; x++)
          {
            Uint8 br = row[x * 3 + 0 + 2]; // assume RGB24
            Uint8 bg = row[x * 3 + 1 + 2 - 1];
            Uint8 bb = row[x * 3 + 2 + 2 - 2];
            if (br == 20 && bg == 22 && bb == 35)
              sky_pixels++;
          }
        }
        double sky_ratio = (double)sky_pixels / (double)total;
        printf("[universe-ref] fp-ideal-opt sky_ratio=%.3f\n", sky_ratio);
      }
    }
  }

  // CPU Optimization Phases (if enabled)
  if (cpu_optimization_phases) {
    printf("\n[universe-ref] === CPU OPTIMIZATION PHASES ===\n");
    render_cpu_optimization_phases(ren, ir, W, H);
    printf("[universe-ref] CPU optimization phases completed!\n");
  }

  // Sprite Renderer Optimization Phases (if enabled)
  if (sprite_optimization_phases) {
    printf("\n[universe-ref] === SPRITE RENDERER OPTIMIZATION PHASES ===\n");
    render_sprite_optimization_phases(ren, ir, W, H);
    printf("[universe-ref] Sprite renderer optimization phases completed!\n");
  }

  // World Type Reference Generation (if enabled)
  if (world_type_references) {
    printf("\n[universe-ref] === WORLD TYPE REFERENCE GENERATION ===\n");
    generate_world_type_references(ren, ir, W, H);
    printf("[universe-ref] World type reference generation completed!\n");
  }

  // Summary of all generated files
  printf("\n[universe-ref] === GENERATED FILES SUMMARY ===\n");
  printf("[universe-ref] Bitmap outputs (assets/):\n");
  printf("[universe-ref]   - current.bmp (isometric view)\n");
  printf("[universe-ref]   - reference.bmp (isometric reference)\n");
  printf("[universe-ref]   - current_fp.bmp (first-person view)\n");
  printf("[universe-ref]   - reference_fp.bmp (first-person reference)\n");
  printf("[universe-ref]   - current_fp_ideal.bmp (ideal first-person)\n");
  printf("[universe-ref]   - reference_fp_ideal.bmp (ideal reference)\n");
  printf("[universe-ref]   - current_fp_ideal_opt.bmp (optimized ideal)\n");
  if (cpu_optimization_phases) {
    printf("[universe-ref]   - cpu_phase_none.bmp (no optimizations)\n");
    printf("[universe-ref]   - cpu_phase_chunk.bmp (chunk culling)\n");
    printf("[universe-ref]   - cpu_phase_screen.bmp (screen culling)\n");
    printf("[universe-ref]   - cpu_phase_color.bmp (color table)\n");
    printf("[universe-ref]   - cpu_phase_batch.bmp (batch rendering)\n");
    printf("[universe-ref]   - cpu_phase_loop.bmp (loop unrolling)\n");
    printf("[universe-ref]   - cpu_phase_memory.bmp (memory alignment)\n");
    printf("[universe-ref]   - cpu_phase_simd.bmp (SIMD hints)\n");
    printf("[universe-ref]   - cpu_phase_cache.bmp (cache optimization)\n");
    printf("[universe-ref]   - cpu_phase_all.bmp (all optimizations)\n");
  }
  if (sprite_optimization_phases) {
    printf("[universe-ref]   - sprite_phase_none.bmp (no optimizations)\n");
    printf("[universe-ref]   - sprite_phase_screen.bmp (screen culling)\n");
    printf("[universe-ref]   - sprite_phase_cache.bmp (sprite caching)\n");
    printf("[universe-ref]   - sprite_phase_batch.bmp (batch rendering)\n");
    printf("[universe-ref]   - sprite_phase_depth.bmp (depth sorting)\n");
    printf("[universe-ref]   - sprite_phase_all.bmp (all optimizations)\n");
  }
  if (world_type_references) {
    printf("[universe-ref]   - world_type_home.bmp (home world reference)\n");
    printf("[universe-ref]   - world_type_farm.bmp (farm world reference)\n");
    printf("[universe-ref]   - world_type_random.bmp (random world reference)\n");
    printf("[universe-ref]   - world_type_wilderness.bmp (wilderness world reference)\n");
    printf("[universe-ref]   - world_type_solid.bmp (solid world reference)\n");
    printf("[universe-ref]   - world_type_underworld.bmp (underworld world reference)\n");
    printf("[universe-ref]   - world_type_scoured.bmp (scoured world reference)\n");
    printf("[universe-ref]   - world_type_labyrinth.bmp (labyrinth world reference)\n");
    printf("[universe-ref]   - world_type_wfc_town.bmp (WFC town world reference)\n");
    printf("[universe-ref]   - world_type_cloud.bmp (cloud world reference)\n");
    printf("[universe-ref]   - world_type_arena.bmp (arena world reference)\n");
    printf("[universe-ref]   - topdown_home.bmp (home world top-down)\n");
    printf("[universe-ref]   - topdown_farm.bmp (farm world top-down)\n");
    printf("[universe-ref]   - topdown_wilderness.bmp (wilderness world top-down)\n");
    printf("[universe-ref]   - topdown_arena.bmp (arena world top-down)\n");
  }
  printf("[universe-ref] Mesh outputs (assets/):\n");
  printf("[universe-ref]   - voxel_mesh_test.obj (test world mesh)\n");
  printf("[universe-ref]   - voxel_mesh_debug.obj (reference world mesh)\n");
  printf("[universe-ref]   - voxel_mesh_fp.obj (first-person view mesh, if mesh mode enabled)\n");
  printf("[universe-ref] Performance reports (reports/):\n");
  printf("[universe-ref]   - reference-render.json (timing data)\n");
  printf("[universe-ref] All files are saved in the assets/ directory for easy access.\n");

  if (rgb_ref)
    SDL_FreeSurface(rgb_ref);
  SDL_FreeSurface(surf32);
  if (ref_loaded)
    SDL_FreeSurface(ref_loaded);
  if (cur_loaded)
    SDL_FreeSurface(cur_loaded);
  SDL_DestroyTexture(target);
  isometric_renderer_destroy(ir);
  game_worlds_destroy(gw);

  // Cleanup test world (only when flag is set)
  // No longer needed since we're modifying the home world directly

  SDL_DestroyRenderer(ren);
  SDL_DestroyWindow(win);
  SDL_Quit();
  return 0;
}
