#ifndef VULKAN_SHADERS_H
#define VULKAN_SHADERS_H

// Vertex shader for voxel rendering
static const char* VOXEL_VERTEX_SHADER =
"#version 450\n"
"\n"
"layout(location = 0) in vec3 inPosition;\n"
"layout(location = 1) in vec3 inNormal;\n"
"layout(location = 2) in vec4 inColor;\n"
"layout(location = 3) in vec2 inTexCoord;\n"
"\n"
"layout(location = 0) out vec3 fragPos;\n"
"layout(location = 1) out vec3 fragNormal;\n"
"layout(location = 2) out vec4 fragColor;\n"
"layout(location = 3) out vec2 fragTexCoord;\n"
"\n"
"layout(set = 0, binding = 0) uniform UniformBufferObject {\n"
"    mat4 view;\n"
"    mat4 proj;\n"
"    mat4 model;\n"
"    vec4 cameraPos;\n"
"    vec4 lightPos;\n"
"    float time;\n"
"} ubo;\n"
"\n"
"void main() {\n"
"    vec4 worldPos = ubo.model * vec4(inPosition, 1.0);\n"
"    gl_Position = ubo.proj * ubo.view * worldPos;\n"
"\n"
"    fragPos = worldPos.xyz;\n"
"    fragNormal = mat3(ubo.model) * inNormal;\n"
"    fragColor = inColor;\n"
"    fragTexCoord = inTexCoord;\n"
"}\n";

// Fragment shader for voxel rendering with lighting
static const char* VOXEL_FRAGMENT_SHADER =
"#version 450\n"
"\n"
"layout(location = 0) in vec3 fragPos;\n"
"layout(location = 1) in vec3 fragNormal;\n"
"layout(location = 2) in vec4 fragColor;\n"
"layout(location = 3) in vec2 fragTexCoord;\n"
"\n"
"layout(location = 0) out vec4 outColor;\n"
"\n"
"layout(set = 0, binding = 0) uniform UniformBufferObject {\n"
"    mat4 view;\n"
"    mat4 proj;\n"
"    mat4 model;\n"
"    vec4 cameraPos;\n"
"    vec4 lightPos;\n"
"    float time;\n"
"} ubo;\n"
"\n"
"void main() {\n"
"    // Normalize the normal vector\n"
"    vec3 N = normalize(fragNormal);\n"
"\n"
"    // Light direction\n"
"    vec3 L = normalize(ubo.lightPos.xyz - fragPos);\n"
"\n"
"    // View direction\n"
"    vec3 V = normalize(ubo.cameraPos.xyz - fragPos);\n"
"\n"
"    // Half-way vector for Blinn-Phong\n"
"    vec3 H = normalize(L + V);\n"
"\n"
"    // Ambient lighting\n"
"    float ambientStrength = 0.2;\n"
"    vec3 ambient = ambientStrength * fragColor.rgb;\n"
"\n"
"    // Diffuse lighting\n"
"    float diff = max(dot(N, L), 0.0);\n"
"    vec3 diffuse = diff * fragColor.rgb;\n"
"\n"
"    // Specular lighting (Blinn-Phong)\n"
"    float spec = pow(max(dot(N, H), 0.0), 32.0);\n"
"    vec3 specular = spec * vec3(1.0, 1.0, 1.0);\n"
"\n"
"    // Combine lighting components\n"
"    vec3 result = ambient + diffuse + specular;\n"
"\n"
"    // Add some fog effect based on distance\n"
"    float distance = length(ubo.cameraPos.xyz - fragPos);\n"
"    float fogFactor = exp(-distance * 0.01);\n"
"    fogFactor = clamp(fogFactor, 0.0, 1.0);\n"
"\n"
"    vec3 fogColor = vec3(0.7, 0.8, 1.0);\n"
"    result = mix(fogColor, result, fogFactor);\n"
"\n"
"    outColor = vec4(result, fragColor.a);\n"
"}\n";

// Vertex shader for UI/overlay rendering
static const char* UI_VERTEX_SHADER =
"#version 450\n"
"\n"
"layout(location = 0) in vec2 inPosition;\n"
"layout(location = 1) in vec2 inTexCoord;\n"
"\n"
"layout(location = 0) out vec2 fragTexCoord;\n"
"\n"
"void main() {\n"
"    gl_Position = vec4(inPosition, 0.0, 1.0);\n"
"    fragTexCoord = inTexCoord;\n"
"}\n";

// Fragment shader for UI/overlay rendering
static const char* UI_FRAGMENT_SHADER =
"#version 450\n"
"\n"
"layout(location = 0) in vec2 fragTexCoord;\n"
"\n"
"layout(location = 0) out vec4 outColor;\n"
"\n"
"layout(set = 0, binding = 1) uniform sampler2D texSampler;\n"
"\n"
"void main() {\n"
"    outColor = texture(texSampler, fragTexCoord);\n"
"}\n";

// Compute shader for voxel ray marching (optional)
static const char* VOXEL_RAY_MARCH_COMPUTE_SHADER =
"#version 450\n"
"\n"
"layout(local_size_x = 16, local_size_y = 16) in;\n"
"\n"
"layout(set = 0, binding = 2) uniform UniformBufferObject {\n"
"    mat4 view;\n"
"    mat4 proj;\n"
"    mat4 model;\n"
"    vec4 cameraPos;\n"
"    vec4 lightPos;\n"
"    float time;\n"
"} ubo;\n"
"\n"
"layout(set = 0, binding = 3) buffer VoxelData {\n"
"    uint data[];\n"
"} voxels;\n"
"\n"
"layout(set = 0, binding = 4) uniform VoxelWorldInfo {\n"
"    uint width;\n"
"    uint height;\n"
"    uint depth;\n"
"    float voxel_size;\n"
"} world;\n"
"\n"
"layout(set = 0, binding = 5) uniform writeonly image2D outputImage;\n"
"\n"
"// Ray marching constants\n"
"const float MAX_DISTANCE = 1000.0;\n"
"const float EPSILON = 0.001;\n"
"\n"
"// Get voxel at position\n"
"uint getVoxel(vec3 pos) {\n"
"    ivec3 voxelPos = ivec3(pos / world.voxel_size);\n"
"\n"
"    if (voxelPos.x < 0 || voxelPos.x >= int(world.width) ||\n"
"        voxelPos.y < 0 || voxelPos.y >= int(world.height) ||\n"
"        voxelPos.z < 0 || voxelPos.z >= int(world.depth)) {\n"
"        return 0; // Air\n"
"    }\n"
"\n"
"    uint index = voxelPos.x + voxelPos.y * world.width + voxelPos.z * world.width * world.height;\n"
"    return voxels.data[index];\n"
"}\n"
"\n"
"// Ray marching function\n"
"vec4 rayMarch(vec3 origin, vec3 direction) {\n"
"    vec3 pos = origin;\n"
"\n"
"    for (int i = 0; i < 256; i++) {\n"
"        uint voxel = getVoxel(pos);\n"
"\n"
"        if (voxel != 0) {\n"
"            // Hit a solid voxel\n"
"            vec3 normal = vec3(0.0);\n"
"\n"
"            // Calculate normal by checking neighboring voxels\n"
"            if (getVoxel(pos + vec3(EPSILON, 0, 0)) == 0) normal.x = 1.0;\n"
"            if (getVoxel(pos + vec3(-EPSILON, 0, 0)) == 0) normal.x = -1.0;\n"
"            if (getVoxel(pos + vec3(0, EPSILON, 0)) == 0) normal.y = 1.0;\n"
"            if (getVoxel(pos + vec3(0, -EPSILON, 0)) == 0) normal.y = -1.0;\n"
"            if (getVoxel(pos + vec3(0, 0, EPSILON)) == 0) normal.z = 1.0;\n"
"            if (getVoxel(pos + vec3(0, 0, -EPSILON)) == 0) normal.z = -1.0;\n"
"\n"
"            normal = normalize(normal);\n"
"\n"
"            // Simple lighting\n"
"            float light = max(0.0, dot(normal, normalize(ubo.lightPos.xyz - pos)));\n"
"            vec3 color = vec3(0.5 + 0.5 * light);\n"
"\n"
"            return vec4(color, 1.0);\n"
"        }\n"
"\n"
"        pos += direction * world.voxel_size;\n"
"\n"
"        if (length(pos - origin) > MAX_DISTANCE) {\n"
"            break;\n"
"        }\n"
"    }\n"
"\n"
"    // No hit, return sky color\n"
"    return vec4(0.7, 0.8, 1.0, 1.0);\n"
"}\n"
"\n"
"void main() {\n"
"    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);\n"
"    ivec2 imageSize = imageSize(outputImage);\n"
"\n"
"    if (pixelCoord.x >= imageSize.x || pixelCoord.y >= imageSize.y) {\n"
"        return;\n"
"    }\n"
"\n"
"    // Calculate ray direction\n"
"    vec2 texCoord = (vec2(pixelCoord) + 0.5) / vec2(imageSize);\n"
"    vec2 clipCoord = texCoord * 2.0 - 1.0;\n"
"\n"
"    vec4 rayStart = ubo.proj * ubo.view * vec4(0.0, 0.0, 0.0, 1.0);\n"
"    vec4 rayEnd = ubo.proj * ubo.view * vec4(clipCoord.x, clipCoord.y, 1.0, 1.0);\n"
"\n"
"    vec3 rayDir = normalize(rayEnd.xyz - rayStart.xyz);\n"
"\n"
"    // Perform ray marching\n"
"    vec4 color = rayMarch(ubo.cameraPos.xyz, rayDir);\n"
"\n"
"    // Output result\n"
"    imageStore(outputImage, pixelCoord, color);\n"
"}\n";

#endif // VULKAN_SHADERS_H
