name: Test
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Install Node.js on ${{ matrix.os }}
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Generate coverage report
      run: npm run report:coverage:ci
    - name: Send coverage report
      continue-on-error: true
      uses: codecov/codecov-action@v4
      with:
        directory: ./reports/
        fail_ci_if_error: false
